In [21]:
import pandas as pd
import numpy as np
from functools import reduce
import datetime
from datetime import datetime

In [22]:
data1=pd.read_excel("RELATED_ENTITIES_01282020.xlsx")
data2=pd.read_excel("AMER_CLIENTS_01282020.xlsx")

In [23]:
new_header = data1.iloc[0] #grab the first row for the header
data1 = data1[1:] #take the data less the header row
data1.columns = new_header #set the header row as the df header

data1=data1.rename(columns={"KYC Entities parent Full Legal Name":"Company Name *",
                     "KYC Entities parent Postal Code":"ZipPostal",
                     "KYC Entities parent Registered Address - Street":"Address",
                     "KYC Entities parent State Name":"StateProv",
                     "KYC Entities parent City Name":"City",
                     "KYC Entities Country of Residence":"Country"})


new_header = data2.iloc[0] #grab the first row for the header
data2 = data2[1:] #take the data less the header row
data2.columns = new_header #set the header row as the df header
data2



data2=data2.rename(columns={"BDR EL Id": "Submission Id","BDR EL Full Legal Name":"Company Name *",
                     "BDR EL Addresses Registered Street Name":"Address",
                     "BDR EL Addresses Registered State Name":"StateProv",
                     "BDR EL Addresses Registered Postal Code":"ZipPostal",
                     "BDR EL Addresses Registered Country":"Country",
                     "BDR EL Addresses Registered City Name":"City",
                     "BDR EL Addresses Business Street Name":"Location 1 Address",
                     "BDR EL Addresses Business State Name":"Location 1 StateProv",
                     "BDR EL Addresses Business Postal Code":"Location 1 ZipPostal",
                           "BDR EL Addresses Business Country":"Location 1 Country",
                           "BDR EL Addresses Business City Name":"Location 1 City"})

In [128]:
data1[0:20]

,Company Name *,Address,City,StateProv,ZipPostal,Country,identifier
1,"10036803 Canada Inc.,",NaN,NaN,NaN,NaN,CANADA ...,B-1
2,"101 MERRIMAC HOLDINGS, LLC",NaN,-,NaN,-,UNITED STATES OF AMERICA ...,B-2
3,"101 MERRIMAC, INC",NaN,-,NaN,-,UNITED STATES OF AMERICA ...,B-3
4,"101 MERRIMAC, LLC",NaN,-,NaN,-,UNITED STATES OF AMERICA ...,B-4
5,1029 GEARY JV LLC,NaN,WILMINGTON,DELAWARE,19801,UNITED STATES OF AMERICA ...,B-5
6,1029 GEARY STREET PROPERTY LLC,NaN,WILMINGTON,DELAWARE,19801,UNITED STATES OF AMERICA ...,B-6
7,10614408 CANADA LIMITED,NaN,Toronto,NaN,ON M5H 3Y2,CANADA ...,B-7
8,10814253 CANADA INC.,NaN,NaN,NaN,NaN,UNITED STATES OF AMERICA ...,B-8
9,1102952 B.C. Unlimited Liability Company,NaN,NaN,NaN,NaN,CANADA ...,B-9
10,1185-9576 QUEBEC INC,NaN,LEVIS,NaN,G6V8V6,CANADA ...,B-10
11,1212770 BC Ltd,NaN,NaN,NaN,NaN,CANADA ...,B-11
12,1625 EYE STREET GP LLC,NaN,DOVER,NaN,19904,UNITED STATES OF AMERICA ...,B-12
13,1625 EYE STREET HOLDINGS LLC,NaN,DOVER,NaN,19904,UNITED STATES OF AMERICA ...,B-13
14,1625 EYE STREET INVESTMENTS LIMITED,NaN,GUERNSEY,NaN,GY1 3NF,"GUERNSEY, C.I ...",B-14
15,1625 EYE STREET L.P.,NaN,DOVER,NaN,19904,UNITED STATES OF AMERICA ...,B-15
16,16 Tech Community Corporation,NaN,Indianapolis,NaN,NaN,UNITED STATES OF AMERICA ...,B-16
17,1706065 ALBERTA ULC,NaN,TORONTO,ON,MJ5 2T3,CANADA ...,B-17
18,1706065 ALBERTA ULC,NaN,NaN,NaN,NaN,CANADA ...,B-18
19,1706065 CANADA ULC,NaN,,NaN,,CANADA ...,B-19
20,1706065 CANADA ULC,NaN,,NaN,,CANADA ...,B-20

In [25]:
data1=data1[["Company Name *","Address","City","StateProv","ZipPostal","Country","identifier"]]
data2=data2[["Submission Id","Company Name *","Address","City","StateProv","ZipPostal","Country","Location 1 Address","Location 1 StateProv","Location 1 ZipPostal","Location 1 Country","Location 1 City","identifier"]]
data=pd.concat([data1,data2], join="outer")

/Users/ljiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until

In [26]:
len(data1)+len(data2)

27668

In [27]:
data["Address"]=data["Address"].replace("-",np.nan).replace(".",np.nan).replace("n.a.",np.nan).replace("NA",np.nan).replace("n.a",np.nan).replace("N/A",np.nan).replace("na",np.nan)
data["City"]=data["City"].replace("-",np.nan).replace("--",np.nan).replace("?NA",np.nan).replace(".",np.nan).replace("n.a.",np.nan).replace("NA",np.nan).replace("n.a",np.nan).replace("N/A",np.nan).replace("na",np.nan)
data["Location 1 ZipPostal"]=data["Location 1 ZipPostal"].replace("-",np.nan).replace("n.a.",np.nan).replace("NA",np.nan).replace("n.a",np.nan).replace("N/A",np.nan).replace("na",np.nan)
data["ZipPostal"]=data["ZipPostal"].replace("-",np.nan).replace("--",np.nan).replace(".",np.nan).replace("..",np.nan).replace("n.a.",np.nan).replace("NA",np.nan).replace("n.a",np.nan).replace("N/A",np.nan).replace("na",np.nan)
data["StateProv"]=data["StateProv"].replace("-",np.nan).replace(".",np.nan).replace("n.a.",np.nan).replace("NA",np.nan).replace("n.a",np.nan).replace("N/A",np.nan).replace("na",np.nan)

In [28]:
data_new=data.copy()

# TRIM Company Name

In [29]:
# s1=" AB "
# s2=s1.strip()
# s2

In [30]:
# #country_name
# name="A    S.Inc.     "
# str1=name.split()  
# new_string=" ".join(str1)
# new_string

In [31]:
## check for the nan in name
new_name=[]
name2=[]
index2=[]
name=data_new['Company Name *'].to_list()
for i in range(len(name)):
    if type(name[i])==float:
        name2.append(name[i])
        index2.append(i)
index2

[10153]

In [32]:
data_new.iloc[10153]
# # # ## may change in future manual 
# data_new=data_new.drop(10152)
#data_new=data_new.reset_index(drop=True)

Address                                                               NaN
City                                                                  NaN
Company Name *                                                        NaN
Country                 CANADA                                        ...
Location 1 Address                                                    NaN
Location 1 City                                                       NaN
Location 1 Country                                                    NaN
Location 1 StateProv                                                  NaN
Location 1 ZipPostal                                                  NaN
StateProv                                                             NaN
Submission Id                                                         NaN
ZipPostal                                                             NaN
identifier                                                        B-10154
Name: 10154, dtype: object

In [33]:
## name clean
data_new['Company Name *']=data_new['Company Name *'].astype(str)
name=data_new["Company Name *"].to_list()
new_name=[]

for i in range(len(name)):
    str1=name[i].split()  
    new_string=" ".join(str1)
    new_name.append(new_string)
data_new["Company Name *"]=new_name
print("done")

done

# Strip the Last Punctuation

In [34]:
## doing twice strip last punctuation, takes seconds to run

In [35]:
import string
punc_lst=[",","."]
def strip_last_punctuation(s):
    if s and s[-1] in punc_lst:
        return s[:-1]
    else:
        return s

test_str = "BROWN BROTHERS HARRIMAN & CO)."
print(strip_last_punctuation(test_str))

BROWN BROTHERS HARRIMAN & CO)

In [36]:
## strip once
test=data_new["Company Name *"].to_list()
lst=[]
for i in range(0,len(test)):
    lst.append(strip_last_punctuation(test[i]))
    
## strip twice
lst1=[]
for i in range(0,len(lst)):
    lst1.append(strip_last_punctuation(lst[i]))
##UPDATE company name
data_new['Company Name *'] = lst1
data_new["Company Name *"]=data_new["Company Name *"].str.upper()

In [37]:
# len(lst)
data_new["Company Name *"]=data_new["Company Name *"].str.upper()
data_new['Company Name *']

1                                      10036803 CANADA INC
2                               101 MERRIMAC HOLDINGS, LLC
3                                        101 MERRIMAC, INC
4                                        101 MERRIMAC, LLC
5                                        1029 GEARY JV LLC
6                           1029 GEARY STREET PROPERTY LLC
7                                  10614408 CANADA LIMITED
8                                      10814253 CANADA INC
9                 1102952 B.C. UNLIMITED LIABILITY COMPANY
10                                    1185-9576 QUEBEC INC
11                                          1212770 BC LTD
12                                  1625 EYE STREET GP LLC
13                            1625 EYE STREET HOLDINGS LLC
14                     1625 EYE STREET INVESTMENTS LIMITED
15                                     1625 EYE STREET L.P
16                           16 TECH COMMUNITY CORPORATION
17                                     1706065 ALBERTA ULC
18                                     1706065 ALBERTA ULC
19                                      1706065 CANADA ULC
20                                      1706065 CANADA ULC
21                                       171263 CANADA INC
22                                     1799101 ONTARIO INC
23                                       17 DECATUR JV LLC
24                          17 DECATUR STREET PROPERTY LLC
25                                          17 H20PARTNERS
26                                  180 MAIDEN LANE JV LLC
27                        1867 INFRASTRUCTURE HOLDINGS INC
28                                   1867 NA30 HOLDING INC
29                          1867 NOUVELLE AUTOROUTE 30 INC
30                               1900 HOLDINGS CORPORATION
                               ...
11759                                   BCORE PARADISE LLC
11760    BFM A/C FREDDIE MAC STACR TRUST 2019-FTR3 - L-...
11761    BFM A/C FREDDIE MAC STACR TRUST 2019-FTR4 - L-...
11762                              JEPPESEN SANDERSON, INC
11763    SOCIEDADE BENEF ISRAELITABRAS HOSPITAL ALBERT ...
11764    T.ROWE PRICE ASSOCIATES INC AC METROPOLITAN LI...
11765                                     KAYNE CLO 4, LTD
11766                                     KAYNE CLO 6, LTD
11767                                     KAYNE CLO I, LTD
11768                                    KAYNE CLO II, LTD
11769                                   KAYNE CLO III, LTD
11770                        DEVILLE HOTEIS E TURISMO LTDA
11771                   HUNT OIL COMPANY NORTH AMERICA LLC
11772                   WHISKEY BAY GATHERING COMPANY, LLC
11773    TRAP A/C KOREA INVESTMENT CORPORATION - AIDELT...
11774    TRPA A/C JP MORGAN CHASE & CO - JPMORGAN CHASE...
11775    JIANGSU ZHONGHENG PET ARTICLES JOINT STOCK CO LTD
11776                  SABLE INTERNATIONAL FINANCE LIMITED
11777                GREAT LAKES PORTMAN RIDGE FUNDING LLC
11778                     ROKOS CAPITAL MANAGEMENT (US) LP
11779    MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD., ...
11780                              SCHLUMBERGER FINANCE NV
11781             PARTNERRE - CHARTIS OVERSEAS ASSOCIATION
11782                 PARTNER RE - NATIONAL UNION FIRE INS
11783                       PARTNERRE FBO LINCOLN NATIONAL
11784    PARTNER REINSURANCE EUROPE SE MORTGAGE BACKED SEC
11785    PARTNERRE CO LTD - PARTNERRE CO US MORTGAGE BA...
11786                                        PARTNERRE LTD
11787                   PARTNER REINSURANCE US CORPORATION
11788    NEUBERGER BERMAN INVESTMENT FUNDS PLC- NEUBERG...
Name: Company Name *, Length: 27668, dtype: object

In [38]:
#data_new.to_excel("check3.xlsx")

# Group on the Company Name

In [39]:
# ## need to be completed the grouping
# b=data.groupby(['Company Name *']).agg({'Submission ID (BDR Id or "KAP")':'unique',
#                                         'Address':'unique',
#                                         'City':'unique',
#                                          'StateProv':"unique",
#                                        'ZipPostal':"unique","Country":"unique"})

In [40]:
# b

# Top Row Identify

In [41]:
# #data_new=data.copy()
# data_new
# data_new=data_new.sort_values(by='Company Name *').reset_index(drop=True)
# data_new

In [42]:
# ## QAed Running Fine
# data_new["Top"]=np.nan
# for i in range(1,len(data_new)):
#     if data_new["Company Name *"][i-1]==data_new["Company Name *"][i]:
#         data_new["Top"][i]="+"
#     else: 
#         #data_new["Top"][i]="top"
#         if (data_new["Company Name *"][i-1]!=data_new["Company Name *"][i])&(data_new["Company Name *"][i+1]!=data_new["Company Name *"][i]):
#             data_new["Top"][i]="Single"
#         else:
#             data_new["Top"][i]="Top"
# print("done")

In [43]:
# # ## whole run QA
# data_new.to_excel("refresh_QA3.xlsx")

In [44]:
# ## input of the country clean
# data_new=pd.read_excel("refresh_QA3.xlsx")
# data_new

# Country clean

In [45]:
#data_new=data.copy()
#data=pd.read_excel("Copy of DDIQ_Jan2019_EligiblePop.xlsx",sheet_name="Company Full Submission")
country=pd.read_excel("country_name.xlsx")
country['country'] = country['country'].str.upper()
country['name'] = country['name'].str.upper()
data_new["Country"] = data_new["Country"].str.upper()
country=country.drop(["Unnamed: 0"],axis=1)
country
# data_new["Country"]

,country,variable,name
0,AFGHANISTAN,0,ISLAMIC REPUBLIC OF AFGHANISTAN
1,ALAND ISLANDS,1,ÅLAND
2,ALAND ISLANDS,0,PROVINCE OF ÅLAND
3,ALBANIA,0,REPUBLIC OF ALBANIA
4,ALGERIA,0,PEOPLE’S DEMOCRATIC REPUBLIC OF ALGERIA
5,ANDORRA,0,PRINCIPALITY OF ANDORRA
6,ANGOLA,0,REPUBLIC OF ANGOLA
7,ARGENTINA,0,ARGENTINE REPUBLIC
8,ARMENIA,0,REPUBLIC OF ARMENIA
9,AUSTRALIA,0,COMMONWEALTH OF AUSTRALIA
10,AUSTRIA,0,REPUBLIC OF AUSTRIA
11,AZERBAIJAN,0,REPUBLIC OF AZERBAIJAN
12,BAHAMAS,1,THE BAHAMAS
13,BAHAMAS,0,COMMONWEALTH OF THE BAHAMAS
14,BAHRAIN,0,KINGDOM OF BAHRAIN
15,BELARUS,0,REPUBLIC OF BELARUS
16,BELGIUM,0,KINGDOM OF BELGIUM
17,BENIN,0,REPUBLIC OF BENIN
18,BERMUDA,1,SOMERS ISLANDS
19,BERMUDA,0,SOMERS ISLES
20,BHUTAN,0,KINGDOM OF BHUTAN
21,BOLIVIA,1,REPUBLIC OF BOLIVIA
22,BOLIVIA,0,PLURINATIONAL STATE OF BOLIVIA
23,"BONAIRE, SAINT EUSTATIUS AND SABA",1,SAINT EUSTATIUS
24,"BONAIRE, SAINT EUSTATIUS AND SABA",3,SABA
25,"BONAIRE, SAINT EUSTATIUS AND SABA",2,SINT EUSTATIUS
26,"BONAIRE, SAINT EUSTATIUS AND SABA",5,BES ISLANDS
27,"BONAIRE, SAINT EUSTATIUS AND SABA",4,SAINT EUSTATIUS AND SABA
28,"BONAIRE, SAINT EUSTATIUS AND SABA",0,BONAIRE
29,BOTSWANA,0,REPUBLIC OF BOTSWANA
...,...,...,...
279,UNITED KINGDOM,5,G.B.
280,UNITED KINGDOM,1,GREAT BRITAIN
281,UNITED STATES,0,U.S.
282,UNITED STATES,1,UNITED STATES OF AMERICA
283,UNITED STATES,3,U.S.A.
284,UNITED STATES,2,THE UNITED STATES OF AMERICA
285,UNITED STATES MINOR OUTLYING ISLANDS,0,U.S. MINOR OUTLYING ISLANDS
286,URUGUAY,0,ORIENTAL REPUBLIC OF URUGUAY
287,UZBEKISTAN,0,REPUBLIC OF UZBEKISTAN
288,VANUATU,0,REPUBLIC OF VANUATU
289,VENEZUELA,2,REPUBLIC OF VENEZUELA
290,VENEZUELA,0,BOLIVARIAN REPUBLIC OF VENEZUELA
291,VENEZUELA,1,UNITED STATES OF VENEZUELA
292,VIETNAM,0,VIET NAM
293,VIETNAM,1,SOCIALIST REPUBLIC OF VIETNAM
294,VIRGIN ISLANDS (UK),2,BVI
295,VIRGIN ISLANDS (UK),3,B.V.I.
296,VIRGIN ISLANDS (UK),1,"VIRGIN ISLANDS, BRITISH"
297,VIRGIN ISLANDS (UK),0,BRITISH VIRGIN ISLANDS
298,VIRGIN ISLANDS (US),0,U.S. VIRGIN ISLANDS
299,VIRGIN ISLANDS (US),2,VIRGIN ISLANDS OF THE UNITED STATES
300,VIRGIN ISLANDS (US),1,UNITED STATES VIRGIN ISLANDS
301,WALLIS & FUTUNA,0,WALLIS AND FUTUNA
302,WESTERN SAHARA,1,SPANISH SAHARA
303,WESTERN SAHARA,0,SPANISH WESTERN SAHARA
304,YEMEN,0,REPUBLIC OF YEMEN
305,ZAMBIA,1,NORTHERN RHODESIA
306,ZAMBIA,0,REPUBLIC OF ZAMBIA
307,ZIMBABWE,1,SOUTHERN RHODESIA
308,ZIMBABWE,0,REPUBLIC OF ZIMBABWE

In [46]:
## import the country full list
country_name=pd.read_excel("ddiq country name.xlsx")
country_name
country_list=data_new["Country"].to_list()
len(country_list)
three_letter_iso=country_name["3 Letter ISO"].to_list()
len(three_letter_iso)

247

In [47]:

# 3_iso works
## all ran:2m

for i in range(len(country_list)):
    for m in range(len(country_name)):
        if country_list[i]==country_name["3 Letter ISO"][m]:
            country_list[i]=country_name["DDIQ Country Name"][m]
        else:
            country_list[i]=country_list[i]

data_new['Country'] = country_list

data_new["Country"].unique()

array(['CANADA                                                                          ',
       'UNITED STATES OF AMERICA                                                        ',
       'GUERNSEY, C.I                                                                   ',
       'NA                                                                              ',
       'UNKNOWN COUNTRY                                                                 ',
       'UNITED KINGDOM                                                                  ',
       'AUSTRALIA                                                                       ',
       'GERMANY                                                                         ',
       'LUXEMBOURG                                                                      ',
       'SWITZERLAND                                                                     ',
       'NETHERLANDS                                                                     ',
       nan,
       'FRANCE                                                                          ',
       'CAYMAN ISLANDS                                                                  ',
       'SPAIN                                                                           ',
       'CHILE                                                                           ',
       'BELARUS                                                                         ',
       'RUSSIAN FEDERATION                                                              ',
       'SWEDEN                                                                          ',
       'ABU DHABI                                                                       ',
       'UNITED ARAB EMIRATES                                                            ',
       'NEW ZEALAND                                                                     ',
       'BELGIUM                                                                         ',
       'BRAZIL                                                                          ',
       'LIECHTENSTEIN                                                                   ',
       'URUGUAY                                                                         ',
       'HONG KONG                                                                       ',
       'IRELAND                                                                         ',
       'MAURITIUS                                                                       ',
       'COLOMBIA                                                                        ',
       'ITALY                                                                           ',
       'MEXICO                                                                          ',
       'MALAYSIA                                                                        ',
       'BERMUDA                                                                         ',
       'TURKEY                                                                          ',
       'FINLAND                                                                         ',
       'GIBRALTAR                                                                       ',
       'CYPRUS                                                                          ',
       'ARGENTINA                                                                       ',
       'CAMEROON                                                                        ',
       'MOROCCO                                                                         ',
       'NAMIBIA                                                                         ',
       'INDIA                                                                           ',
       'VIRGIN ISLANDS (BRITISH)                                                        ',
       'MALTA                                                                           ',
       'CHINA                                                                           ',
       '(CASH) WORLD                                                                    ',
       'ANDORRA                                                                         ',
       'AUSTRIA                                                                         ',
       'SINGAPORE                                                                       ',
       'DENMARK                                                                         ',
       'JERSEY, C.I.                                                                    ',
       'BAHRAIN                                                                         ',
       'SOUTH AFRICA                                                                    ',
       'ISRAEL                                                                          ',
       'ANGOLA                                                                          ',
       'ISLE OF MAN                                                                     ',
       'ANGUILLA                                                                        ',
       'SAUDI ARABIA                                                                    ',
       'JAPAN                                                                           ',
       'PERU                                                                            ',
       'ECUADOR                                                                         ',
       'POLAND                                                                          ',
       'CURACAO                                                                         ',
       'HONDURAS                                                                        ',
       'PORTUGAL                                                                        ',
       'GUATEMALA                                                                       ',
       'MOZAMBIQUE                                                                      ',
       'PHILIPPINES                                                                     ',
       'ALBANIA                                                                         ',
       'BOTSWANA                                                                        ',
       'GHANA                                                                           ',
       'JAMAICA                                                                         ',
       "KOREA, DEM PEOPLE'S REP.                                                        ",
       'LITHUANIA                                                                       ',
       'MONGOLIA                                                                        ',
       'TANZANIA, UNITED REP. OF                                                        ',
       'UGANDA                                                                          ',
       'SENEGAL                                                                         ',
       'PANAMA                                                                          ',
       'ROMANIA                                                                         ',
       'BAHAMAS                                                                         ',
       'HUNGARY                                                                         ',
       'BULGARIA                                                                        ',
       'TAIWAN                                                                          ',
       'EGYPT                                                                           ',
       'LIBYA                                                                           ',
       'MAURITANIA                                                                      ',
       'MYANMAR                                                                         ',
       'NIGERIA                                                                         ',
       'OMAN                                                                            ',
       'SRI LANKA                                                                       ',
       'SWAZILAND                                                                       ',
       'TRINIDAD AND TOBAGO                                                             ',
       'TUNISIA                                                                         ',
       'CANARIES ISLAND                                                                 ',
       'KOREA, REPUBLIC OF                                                              ',
       'VIRGIN ISLANDS, U.S.                                                            ',
       'CONGO                                                                           ',
       'GREECE                                                                          ',
       'CROATIA                                                                         ',
       'CZECH REPUBLIC                                                                  ',
       'AFGHANISTAN                                                                     ',
       'NORWAY                                                                          ',
       'BARBADOS                                                                        ',
       'EUROPEAN CENTRAL BANK-ECB                                                       ',
       'EQUATORIAL GUINEA                                                               ',
       'CAPE VERDE                                                                      ',
       'KUWAIT                                                                          ',
       'MONACO                                                                          ',
       'QATAR                                                                           ',
       'MADAGASCAR                                                                      ',
       'ESTONIA                                                                         ',
       'VENEZUELA                                                                       ',
       'KAZAKHSTAN                                                                      ',
       'KYRGIZSTAN                                                                      ',
       'DUBAI                                                                           ',
       'BRITISH INDIAN OCEAN TER.                                                       ',
       'MARSHALL ISLAND                                                                 ',
       'MOLDOVA (REPUBLIC OF)                                                           ',
       'RWANDA                                                                          ',
       'MACEDONIA, THE FORMER YU                                                        ',
       'UKRAINE                                                                         ',
       'VIETNAM                                                                         ',
       'INDONESIA                                                                       ',
       'AZERBAIJAN                                                                      ',
       'WORLD                                                                           ',
       'LIBERIA                                                                         ',
       'JORDAN                                                                          ',
       'IVORY COAST                                                                     ',
       'SIERRA LEONE                                                                    ',
       'COSTA RICA                                                                      ',
       'THE STATE OF PALESTINE                                                          ',
       'PUERTO RICO                                                                     ',
       'CHRISTMAS ISLAND                                                                ',
       'United Kingdom', 'Singapore', 'France', 'Germany',
       'Cayman Islands', 'United States', 'Malaysia', 'Luxembourg',
       'Belgium', 'Japan', 'China', 'Switzerland', 'Taiwan',
       'South Korea', 'Canada', 'Austria', 'Spain', 'Netherlands',
       'Australia', 'Finland', 'Italy', 'Gibraltar', 'Hong Kong',
       'Philippines', 'Israel', 'Norway', 'Ireland', 'Sweden', 'Guernsey',
       'Hungary', 'Portugal', 'Brazil', 'Argentina', 'French Polynesia',
       'New Caledonia', 'Guadeloupe', 'Denmark', 'Greece', 'Turkey',
       'Poland', 'Czech Republic', 'Morocco', 'Senegal', 'Ivory Coast',
       'Cameroon', 'South Africa', 'Puerto Rico', 'Mexico', 'Bermuda',
       'Costa Rica', 'Dominican Republic', 'Curacao', 'Colombia', 'Peru',
       'Chile', 'Bolivia', 'Saudi Arabia', 'Bahrain', 'India', 'Thailand',
       'Indonesia', 'New Zealand', 'United Arab Emirates', 'Guinea',
       'Russia', 'Monaco', 'Liberia', 'Kuwait', 'Romania', 'Uruguay',
       'Slovakia', 'El Salvador', 'Isle of Man', 'Jordan', 'Jersey',
       'Slovenia', 'Panama', 'Bahamas', 'Burkina Faso', 'Chad',
       'Madagascar', 'Algeria', 'Ethiopia', 'Estonia', 'Honduras', 'Fiji',
       'Tunisia', 'Vietnam', 'Trinidad and Tobago', 'Ghana', 'Aruba',
       'Benin', 'Réunion', 'Jamaica', 'Virgin Islands (US)', 'Nigeria',
       'Guatemala', 'Papua New Guinea', 'Egypt', 'Cuba', 'Angola',
       'Malta', 'Moldova', 'Qatar', 'Montenegro', 'Virgin Islands (UK)',
       'Mauritania', 'Marshall Islands', 'Belarus', 'Macedonia',
       'Pakistan', 'Equatorial Guinea', 'Barbados', 'Congo - Brazzaville',
       'Mozambique', 'Guinea-Bissau', 'Mongolia', 'Ecuador', 'Cyprus',
       'Cambodia', 'Mauritius', 'Togo', 'Nicaragua', 'Iceland',
       'Anguilla', 'Oman', 'Namibia', 'Serbia', 'Armenia', 'Azerbaijan',
       'Congo - Kinshasa', 'Niger', 'Kenya', 'Mali', 'Guam', 'Macau'],
      dtype=object)

In [48]:
# #### the below cell runs long
# data_new["Country"][243]

In [49]:
## check for the nan in name
new_name=[]
name2=[]
index2=[]
name=data_new['Country'].to_list()
for i in range(len(name)):
    if type(name[i])==float:
        name2.append(name[i])
        index2.append(i)
index2

[158,
 159,
 165,
 166,
 244,
 246,
 254,
 256,
 259,
 303,
 312,
 338,
 339,
 340,
 341,
 342,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 401,
 403,
 425,
 428,
 448,
 451,
 547,
 549,
 551,
 607,
 625,
 678,
 697,
 709,
 732,
 794,
 816,
 895,
 898,
 951,
 1058,
 1079,
 1080,
 1081,
 1082,
 1130,
 1144,
 1145,
 1146,
 1169,
 1201,
 1215,
 1216,
 1340,
 1367,
 1378,
 1448,
 1456,
 1461,
 1500,
 1505,
 1557,
 1616,
 1652,
 1694,
 1735,
 1737,
 1827,
 1840,
 1864,
 1865,
 1872,
 1881,
 1911,
 1998,
 2070,
 2388,
 2415,
 2417,
 2446,
 2447,
 2535,
 2581,
 2585,
 2586,
 2599,
 2786,
 2927,
 2930,
 3014,
 3015,
 3016,
 3073,
 3097,
 3240,
 3276,
 3277,
 3348,
 3349,
 3350,
 3351,
 3352,
 3356,
 3360,
 3363,
 3366,
 3367,
 3369,
 3373,
 3375,
 3384,
 3387,
 3392,
 3460,
 3487,
 3519,
 3526,
 3556,
 3606,
 3614,
 3691,
 3723,
 3735,
 3736,
 3737,
 3738,
 3739,
 3740,
 3741,
 3742,
 3786,
 3822,
 3826,
 3838,
 3855,
 3860,
 3894,
 3928,
 3929,
 3962,
 4003,
 4042,
 4097,
 4104,
 4164,
 4199,
 4211,
 4213,
 4215,
 4221,
 4327,
 4351,
 4365,
 4381,
 4412,
 4440,
 4442,
 4446,
 4468,
 4495,
 4501,
 4504,
 4516,
 4545,
 4546,
 4584,
 4661,
 4677,
 4681,
 4682,
 4690,
 4716,
 4747,
 4779,
 4793,
 4808,
 4826,
 4884,
 4903,
 4904,
 5014,
 5018,
 5060,
 5061,
 5063,
 5107,
 5115,
 5122,
 5123,
 5141,
 5163,
 5176,
 5177,
 5186,
 5204,
 5225,
 5228,
 5231,
 5240,
 5244,
 5329,
 5367,
 5388,
 5407,
 5408,
 5449,
 5533,
 5568,
 5577,
 5579,
 5582,
 5583,
 5586,
 5597,
 5643,
 5652,
 5687,
 5695,
 5718,
 5722,
 5744,
 5745,
 5792,
 5795,
 5844,
 5858,
 5872,
 5901,
 5907,
 5927,
 5952,
 5954,
 5961,
 5972,
 6054,
 6089,
 6108,
 6111,
 6112,
 6117,
 6121,
 6132,
 6151,
 6166,
 6190,
 6211,
 6219,
 6244,
 6245,
 6316,
 6330,
 6352,
 6357,
 6359,
 6388,
 6485,
 6490,
 6492,
 6505,
 6534,
 6547,
 6554,
 6573,
 6581,
 6597,
 6657,
 6680,
 6681,
 6695,
 6713,
 6718,
 6747,
 6750,
 6781,
 6784,
 6793,
 6803,
 6804,
 6808,
 6809,
 6829,
 6851,
 6865,
 6905,
 6939,
 6942,
 7037,
 7038,
 7039,
 7040,
 7121,
 7303,
 7335,
 7339,
 7357,
 7358,
 7397,
 7426,
 7427,
 7455,
 7486,
 7487,
 7488,
 7489,
 7490,
 7492,
 7530,
 7646,
 7647,
 7661,
 7689,
 7762,
 7764,
 7780,
 7854,
 7859,
 7874,
 7875,
 7879,
 7881,
 7889,
 7890,
 7928,
 7970,
 7972,
 8025,
 8030,
 8031,
 8033,
 8052,
 8120,
 8130,
 8160,
 8247,
 8248,
 8257,
 8301,
 8304,
 8330,
 8331,
 8332,
 8403,
 8531,
 8533,
 8538,
 8566,
 8573,
 8577,
 8609,
 8618,
 8619,
 8650,
 8676,
 8682,
 8698,
 8706,
 8707,
 8715,
 8720,
 8752,
 8755,
 8815,
 8817,
 8850,
 8861,
 8863,
 8871,
 8891,
 8893,
 9080,
 9127,
 9141,
 9145,
 9148,
 9163,
 9164,
 9166,
 9255,
 9288,
 9296,
 9303,
 9309,
 9318,
 9390,
 9392,
 9438,
 9526,
 9540,
 9589,
 9602,
 9624,
 9639,
 9766,
 9890,
 9907,
 9950,
 9953,
 9970,
 9972,
 9973,
 9975,
 10013,
 10018,
 10035,
 10037,
 10043,
 10048,
 10062,
 10129,
 10130,
 10134,
 10145,
 10159,
 10160,
 10200,
 10248,
 10249,
 10278,
 10280,
 10282,
 10372,
 10412,
 10422,
 10424,
 10426,
 10428,
 10429,
 10487,
 10504,
 10517,
 10546,
 10548,
 10550,
 10551,
 10631,
 10632,
 10633,
 10634,
 10635,
 10636,
 10637,
 10643,
 10658,
 10662,
 10716,
 10718,
 10834,
 10836,
 10837,
 10838,
 10852,
 10866,
 10874,
 10894,
 10900,
 10918,
 10948,
 10952,
 11059,
 11063,
 11066,
 11068,
 11144,
 11145,
 11164,
 11174,
 11175,
 11210,
 11214,
 11233,
 11305,
 11306,
 11327,
 11403,
 11431,
 11432,
 11433,
 11436,
 11437,
 11440,
 11441,
 11530,
 11532,
 11556,
 11557,
 11561,
 11590,
 11653,
 11783,
 11796,
 11872,
 11880,
 11936,
 11952,
 11953,
 12003,
 12022,
 12023,
 12026,
 12027,
 12028,
 12045,
 12052,
 12111,
 12129,
 12168,
 12169,
 12199,
 12202,
 12229,
 12230,
 12238,
 12239,
 12248,
 12249,
 12250,
 12268,
 12277,
 12278,
 12280,
 12284,
 12289,
 12290,
 12291,
 12292,
 12293,
 12304,
 12306,
 12308,
 12309,
 12311,
 12312,
 12313,
 12314,
 12315,
 12316,
 12317,
 12322,
 12327,
 12329,
 12337,
 12344,
 12358,
 12391,
 12408,
 12433,
 12437,
 12463,
 12474,
 12517,
 12599,
 12604,
 12743,
 12746,
 12758,
 12761,
 12769,
 12779,
 12780,
 12781,
 12819,
 12853,
 12992,
 13006,
 13007,
 13010,
 13011,
 13039,
 13044,
 13066,
 13069,
 13088,
 13180,
 13183,
 13184,
 13267,
 13363,
 13459,
 13473,
 13480,
 13492,
 13519,
 13624,
 13685,
 13706,
 13803,
 13806,
 13830,
 13831,
 13844,
 13847,
 13854,
 13855,
 13857,
 13863,
 13865,
 13881,
 13884,
 13891,
 13912,
 13914,
 13957,
 14039,
 14075,
 14089,
 14092,
 14093,
 14102,
 14134,
 14142,
 14145,
 14147,
 14150,
 14152,
 14165,
 14186,
 14265,
 14274,
 14287,
 14309,
 14436,
 14449,
 14483,
 14484,
 14485,
 14486,
 14487,
 14488,
 14491,
 14492,
 14522,
 14543,
 14554,
 14561,
 14569,
 14575,
 14628,
 14636,
 14763,
 14772,
 14837,
 14894,
 14966,
 15008,
 15036,
 15056,
 15057,
 15067,
 15086,
 15095,
 15129,
 15139,
 15204,
 15290,
 15291,
 15299,
 15316,
 15368,
 15369,
 15375,
 15384,
 15394,
 15407,
 15492,
 15509,
 15511,
 15563,
 15584,
 15585,
 15592,
 15643,
 15659,
 15667,
 15787,
 15840,
 15851,
 15856]

In [50]:
data_new["Country"]=data_new["Country"].astype(str)
data_new["Country"][243]

243    UNITED STATES OF AMERICA                      ...
243                                        United States
Name: Country, dtype: object

In [51]:
data_new["Country"]=data_new["Country"].replace("nan"," ")
data_new["Country"][836]

836    BELGIUM                                       ...
836                                        United States
Name: Country, dtype: object

In [52]:
## country clean trim space

name=data_new["Country"].to_list()
new_country=[]

for i in range(len(name)):
    str1=name[i].split()  
    new_string=" ".join(str1)
    new_country.append(new_string)
data_new["Country"]=new_country
#print("done")

data_new["Country"].unique()

array(['CANADA', 'UNITED STATES OF AMERICA', 'GUERNSEY, C.I', 'NA',
       'UNKNOWN COUNTRY', 'UNITED KINGDOM', 'AUSTRALIA', 'GERMANY',
       'LUXEMBOURG', 'SWITZERLAND', 'NETHERLANDS', '', 'FRANCE',
       'CAYMAN ISLANDS', 'SPAIN', 'CHILE', 'BELARUS',
       'RUSSIAN FEDERATION', 'SWEDEN', 'ABU DHABI',
       'UNITED ARAB EMIRATES', 'NEW ZEALAND', 'BELGIUM', 'BRAZIL',
       'LIECHTENSTEIN', 'URUGUAY', 'HONG KONG', 'IRELAND', 'MAURITIUS',
       'COLOMBIA', 'ITALY', 'MEXICO', 'MALAYSIA', 'BERMUDA', 'TURKEY',
       'FINLAND', 'GIBRALTAR', 'CYPRUS', 'ARGENTINA', 'CAMEROON',
       'MOROCCO', 'NAMIBIA', 'INDIA', 'VIRGIN ISLANDS (BRITISH)', 'MALTA',
       'CHINA', '(CASH) WORLD', 'ANDORRA', 'AUSTRIA', 'SINGAPORE',
       'DENMARK', 'JERSEY, C.I.', 'BAHRAIN', 'SOUTH AFRICA', 'ISRAEL',
       'ANGOLA', 'ISLE OF MAN', 'ANGUILLA', 'SAUDI ARABIA', 'JAPAN',
       'PERU', 'ECUADOR', 'POLAND', 'CURACAO', 'HONDURAS', 'PORTUGAL',
       'GUATEMALA', 'MOZAMBIQUE', 'PHILIPPINES', 'ALBANIA', 'BOTSWANA',
       'GHANA', 'JAMAICA', "KOREA, DEM PEOPLE'S REP.", 'LITHUANIA',
       'MONGOLIA', 'TANZANIA, UNITED REP. OF', 'UGANDA', 'SENEGAL',
       'PANAMA', 'ROMANIA', 'BAHAMAS', 'HUNGARY', 'BULGARIA', 'TAIWAN',
       'EGYPT', 'LIBYA', 'MAURITANIA', 'MYANMAR', 'NIGERIA', 'OMAN',
       'SRI LANKA', 'SWAZILAND', 'TRINIDAD AND TOBAGO', 'TUNISIA',
       'CANARIES ISLAND', 'KOREA, REPUBLIC OF', 'VIRGIN ISLANDS, U.S.',
       'CONGO', 'GREECE', 'CROATIA', 'CZECH REPUBLIC', 'AFGHANISTAN',
       'NORWAY', 'BARBADOS', 'EUROPEAN CENTRAL BANK-ECB',
       'EQUATORIAL GUINEA', 'CAPE VERDE', 'KUWAIT', 'MONACO', 'QATAR',
       'MADAGASCAR', 'ESTONIA', 'VENEZUELA', 'KAZAKHSTAN', 'KYRGIZSTAN',
       'DUBAI', 'BRITISH INDIAN OCEAN TER.', 'MARSHALL ISLAND',
       'MOLDOVA (REPUBLIC OF)', 'RWANDA', 'MACEDONIA, THE FORMER YU',
       'UKRAINE', 'VIETNAM', 'INDONESIA', 'AZERBAIJAN', 'WORLD',
       'LIBERIA', 'JORDAN', 'IVORY COAST', 'SIERRA LEONE', 'COSTA RICA',
       'THE STATE OF PALESTINE', 'PUERTO RICO', 'CHRISTMAS ISLAND',
       'United Kingdom', 'Singapore', 'France', 'Germany',
       'Cayman Islands', 'United States', 'Malaysia', 'Luxembourg',
       'Belgium', 'Japan', 'China', 'Switzerland', 'Taiwan',
       'South Korea', 'Canada', 'Austria', 'Spain', 'Netherlands',
       'Australia', 'Finland', 'Italy', 'Gibraltar', 'Hong Kong',
       'Philippines', 'Israel', 'Norway', 'Ireland', 'Sweden', 'Guernsey',
       'Hungary', 'Portugal', 'Brazil', 'Argentina', 'French Polynesia',
       'New Caledonia', 'Guadeloupe', 'Denmark', 'Greece', 'Turkey',
       'Poland', 'Czech Republic', 'Morocco', 'Senegal', 'Ivory Coast',
       'Cameroon', 'South Africa', 'Puerto Rico', 'Mexico', 'Bermuda',
       'Costa Rica', 'Dominican Republic', 'Curacao', 'Colombia', 'Peru',
       'Chile', 'Bolivia', 'Saudi Arabia', 'Bahrain', 'India', 'Thailand',
       'Indonesia', 'New Zealand', 'United Arab Emirates', 'Guinea',
       'Russia', 'Monaco', 'Liberia', 'Kuwait', 'Romania', 'Uruguay',
       'Slovakia', 'El Salvador', 'Isle of Man', 'Jordan', 'Jersey',
       'Slovenia', 'Panama', 'Bahamas', 'Burkina Faso', 'Chad',
       'Madagascar', 'Algeria', 'Ethiopia', 'Estonia', 'Honduras', 'Fiji',
       'Tunisia', 'Vietnam', 'Trinidad and Tobago', 'Ghana', 'Aruba',
       'Benin', 'Réunion', 'Jamaica', 'Virgin Islands (US)', 'Nigeria',
       'Guatemala', 'Papua New Guinea', 'Egypt', 'Cuba', 'Angola',
       'Malta', 'Moldova', 'Qatar', 'Montenegro', 'Virgin Islands (UK)',
       'Mauritania', 'Marshall Islands', 'Belarus', 'Macedonia',
       'Pakistan', 'Equatorial Guinea', 'Barbados', 'Congo - Brazzaville',
       'Mozambique', 'Guinea-Bissau', 'Mongolia', 'Ecuador', 'Cyprus',
       'Cambodia', 'Mauritius', 'Togo', 'Nicaragua', 'Iceland',
       'Anguilla', 'Oman', 'Namibia', 'Serbia', 'Armenia', 'Azerbaijan',
       'Congo - Kinshasa', 'Niger', 'Kenya', 'Mali', 'Guam', 'Macau'],
      dtype=object)

In [53]:
## further clean
data_new['Country']=data_new['Country'].replace("NA", " ").replace("UNKNOWN COUNTRY"," ").replace("(blank)"," ").replace("(CASH) WORLD", " ").replace("NA"," ").replace("(BLANK)"," ")
data_new['Country']=data_new['Country'].str.upper()
array=data_new['Country'].unique()
array

array(['CANADA', 'UNITED STATES OF AMERICA', 'GUERNSEY, C.I', ' ',
       'UNITED KINGDOM', 'AUSTRALIA', 'GERMANY', 'LUXEMBOURG',
       'SWITZERLAND', 'NETHERLANDS', '', 'FRANCE', 'CAYMAN ISLANDS',
       'SPAIN', 'CHILE', 'BELARUS', 'RUSSIAN FEDERATION', 'SWEDEN',
       'ABU DHABI', 'UNITED ARAB EMIRATES', 'NEW ZEALAND', 'BELGIUM',
       'BRAZIL', 'LIECHTENSTEIN', 'URUGUAY', 'HONG KONG', 'IRELAND',
       'MAURITIUS', 'COLOMBIA', 'ITALY', 'MEXICO', 'MALAYSIA', 'BERMUDA',
       'TURKEY', 'FINLAND', 'GIBRALTAR', 'CYPRUS', 'ARGENTINA',
       'CAMEROON', 'MOROCCO', 'NAMIBIA', 'INDIA',
       'VIRGIN ISLANDS (BRITISH)', 'MALTA', 'CHINA', 'ANDORRA', 'AUSTRIA',
       'SINGAPORE', 'DENMARK', 'JERSEY, C.I.', 'BAHRAIN', 'SOUTH AFRICA',
       'ISRAEL', 'ANGOLA', 'ISLE OF MAN', 'ANGUILLA', 'SAUDI ARABIA',
       'JAPAN', 'PERU', 'ECUADOR', 'POLAND', 'CURACAO', 'HONDURAS',
       'PORTUGAL', 'GUATEMALA', 'MOZAMBIQUE', 'PHILIPPINES', 'ALBANIA',
       'BOTSWANA', 'GHANA', 'JAMAICA', "KOREA, DEM PEOPLE'S REP.",
       'LITHUANIA', 'MONGOLIA', 'TANZANIA, UNITED REP. OF', 'UGANDA',
       'SENEGAL', 'PANAMA', 'ROMANIA', 'BAHAMAS', 'HUNGARY', 'BULGARIA',
       'TAIWAN', 'EGYPT', 'LIBYA', 'MAURITANIA', 'MYANMAR', 'NIGERIA',
       'OMAN', 'SRI LANKA', 'SWAZILAND', 'TRINIDAD AND TOBAGO', 'TUNISIA',
       'CANARIES ISLAND', 'KOREA, REPUBLIC OF', 'VIRGIN ISLANDS, U.S.',
       'CONGO', 'GREECE', 'CROATIA', 'CZECH REPUBLIC', 'AFGHANISTAN',
       'NORWAY', 'BARBADOS', 'EUROPEAN CENTRAL BANK-ECB',
       'EQUATORIAL GUINEA', 'CAPE VERDE', 'KUWAIT', 'MONACO', 'QATAR',
       'MADAGASCAR', 'ESTONIA', 'VENEZUELA', 'KAZAKHSTAN', 'KYRGIZSTAN',
       'DUBAI', 'BRITISH INDIAN OCEAN TER.', 'MARSHALL ISLAND',
       'MOLDOVA (REPUBLIC OF)', 'RWANDA', 'MACEDONIA, THE FORMER YU',
       'UKRAINE', 'VIETNAM', 'INDONESIA', 'AZERBAIJAN', 'WORLD',
       'LIBERIA', 'JORDAN', 'IVORY COAST', 'SIERRA LEONE', 'COSTA RICA',
       'THE STATE OF PALESTINE', 'PUERTO RICO', 'CHRISTMAS ISLAND',
       'UNITED STATES', 'SOUTH KOREA', 'GUERNSEY', 'FRENCH POLYNESIA',
       'NEW CALEDONIA', 'GUADELOUPE', 'DOMINICAN REPUBLIC', 'BOLIVIA',
       'THAILAND', 'GUINEA', 'RUSSIA', 'SLOVAKIA', 'EL SALVADOR',
       'JERSEY', 'SLOVENIA', 'BURKINA FASO', 'CHAD', 'ALGERIA',
       'ETHIOPIA', 'FIJI', 'ARUBA', 'BENIN', 'RÉUNION',
       'VIRGIN ISLANDS (US)', 'PAPUA NEW GUINEA', 'CUBA', 'MOLDOVA',
       'MONTENEGRO', 'VIRGIN ISLANDS (UK)', 'MARSHALL ISLANDS',
       'MACEDONIA', 'PAKISTAN', 'CONGO - BRAZZAVILLE', 'GUINEA-BISSAU',
       'CAMBODIA', 'TOGO', 'NICARAGUA', 'ICELAND', 'SERBIA', 'ARMENIA',
       'CONGO - KINSHASA', 'NIGER', 'KENYA', 'MALI', 'GUAM', 'MACAU'],
      dtype=object)

In [54]:
# country["country"].unique()
# extra_country=country["country"].to_list()
##upper case
country=pd.read_excel("country_name.xlsx")
country_list_ddiq=pd.read_excel("country_list_ddiq.xlsx")
country["country"]=country["country"].str.upper()
country["name"]=country["name"].str.upper()
country_list_ddiq["DDIQ Country Name"]=country_list_ddiq["DDIQ Country Name"].str.upper()
## make the full list
country_ddiq=country["country"].to_list()
country_alias=country["name"].to_list()
country_list_ddiq=country_list_ddiq["DDIQ Country Name"].to_list()
country_full=country_ddiq+country_alias+country_list_ddiq
## deduplicate the list
output = []
for x in country_full:
    if x not in output:
        output.append(x)
len(output)

556

In [55]:
## start to run 5:25 start for all 2m to finish
test=data_new["Country"].str.upper().to_list()
test1=test

## clean last-vlookup
#test=data_new["Country"].to_list()

lst=[]
index=[]
lst_same=[]
index_same=[]
for i in range(len(test1)):
    for m in range(len(country)):
        if (test1[i]==country["name"][m]):
            test1[i]=country["country"][m]
        elif test1[i] not in country_full:
            index.append(i)
            lst.append(test1[i])
        else:
            test1[i]=test1[i]

list_of_tuples = list(zip(index, lst))
df = pd.DataFrame(list_of_tuples, columns = ['index', 'country']) 
df["country"].unique()

array(['GUERNSEY, C.I', ' ', '', 'ABU DHABI', 'VIRGIN ISLANDS (BRITISH)',
       'JERSEY, C.I.', "KOREA, DEM PEOPLE'S REP.",
       'TANZANIA, UNITED REP. OF', 'CANARIES ISLAND',
       'KOREA, REPUBLIC OF', 'VIRGIN ISLANDS, U.S.', 'CONGO',
       'EUROPEAN CENTRAL BANK-ECB', 'KYRGIZSTAN', 'DUBAI',
       'BRITISH INDIAN OCEAN TER.', 'MARSHALL ISLAND',
       'MOLDOVA (REPUBLIC OF)', 'MACEDONIA, THE FORMER YU', 'WORLD',
       'THE STATE OF PALESTINE'], dtype=object)

In [56]:

data_new["Country"]=test1
data_new["Country"].unique()

array(['CANADA', 'UNITED STATES', 'GUERNSEY, C.I', ' ', 'UNITED KINGDOM',
       'AUSTRALIA', 'GERMANY', 'LUXEMBOURG', 'SWITZERLAND', 'NETHERLANDS',
       '', 'FRANCE', 'CAYMAN ISLANDS', 'SPAIN', 'CHILE', 'BELARUS',
       'RUSSIA', 'SWEDEN', 'ABU DHABI', 'UNITED ARAB EMIRATES',
       'NEW ZEALAND', 'BELGIUM', 'BRAZIL', 'LIECHTENSTEIN', 'URUGUAY',
       'HONG KONG', 'IRELAND', 'MAURITIUS', 'COLOMBIA', 'ITALY', 'MEXICO',
       'MALAYSIA', 'BERMUDA', 'TURKEY', 'FINLAND', 'GIBRALTAR', 'CYPRUS',
       'ARGENTINA', 'CAMEROON', 'MOROCCO', 'NAMIBIA', 'INDIA',
       'VIRGIN ISLANDS (BRITISH)', 'MALTA', 'CHINA', 'ANDORRA', 'AUSTRIA',
       'SINGAPORE', 'DENMARK', 'JERSEY, C.I.', 'BAHRAIN', 'SOUTH AFRICA',
       'ISRAEL', 'ANGOLA', 'ISLE OF MAN', 'ANGUILLA', 'SAUDI ARABIA',
       'JAPAN', 'PERU', 'ECUADOR', 'POLAND', 'CURACAO', 'HONDURAS',
       'PORTUGAL', 'GUATEMALA', 'MOZAMBIQUE', 'PHILIPPINES', 'ALBANIA',
       'BOTSWANA', 'GHANA', 'JAMAICA', "KOREA, DEM PEOPLE'S REP.",
       'LITHUANIA', 'MONGOLIA', 'TANZANIA, UNITED REP. OF', 'UGANDA',
       'SENEGAL', 'PANAMA', 'ROMANIA', 'BAHAMAS', 'HUNGARY', 'BULGARIA',
       'TAIWAN', 'EGYPT', 'LIBYA', 'MAURITANIA', 'MYANMAR', 'NIGERIA',
       'OMAN', 'SRI LANKA', 'SWAZILAND', 'TRINIDAD AND TOBAGO', 'TUNISIA',
       'CANARIES ISLAND', 'KOREA, REPUBLIC OF', 'VIRGIN ISLANDS, U.S.',
       'CONGO', 'GREECE', 'CROATIA', 'CZECH REPUBLIC', 'AFGHANISTAN',
       'NORWAY', 'BARBADOS', 'EUROPEAN CENTRAL BANK-ECB',
       'EQUATORIAL GUINEA', 'CAPE VERDE', 'KUWAIT', 'MONACO', 'QATAR',
       'MADAGASCAR', 'ESTONIA', 'VENEZUELA', 'KAZAKHSTAN', 'KYRGIZSTAN',
       'DUBAI', 'BRITISH INDIAN OCEAN TER.', 'MARSHALL ISLAND',
       'MOLDOVA (REPUBLIC OF)', 'RWANDA', 'MACEDONIA, THE FORMER YU',
       'UKRAINE', 'VIETNAM', 'INDONESIA', 'AZERBAIJAN', 'WORLD',
       'LIBERIA', 'JORDAN', 'IVORY COAST', 'SIERRA LEONE', 'COSTA RICA',
       'THE STATE OF PALESTINE', 'PUERTO RICO', 'CHRISTMAS ISLAND',
       'SOUTH KOREA', 'GUERNSEY', 'FRENCH POLYNESIA', 'NEW CALEDONIA',
       'GUADELOUPE', 'DOMINICAN REPUBLIC', 'BOLIVIA', 'THAILAND',
       'GUINEA', 'SLOVAKIA', 'EL SALVADOR', 'JERSEY', 'SLOVENIA',
       'BURKINA FASO', 'CHAD', 'ALGERIA', 'ETHIOPIA', 'FIJI', 'ARUBA',
       'BENIN', 'RÉUNION', 'VIRGIN ISLANDS (US)', 'PAPUA NEW GUINEA',
       'CUBA', 'MOLDOVA', 'MONTENEGRO', 'VIRGIN ISLANDS (UK)',
       'MARSHALL ISLANDS', 'MACEDONIA', 'PAKISTAN', 'CONGO - BRAZZAVILLE',
       'GUINEA-BISSAU', 'CAMBODIA', 'TOGO', 'NICARAGUA', 'ICELAND',
       'SERBIA', 'ARMENIA', 'CONGO - KINSHASA', 'NIGER', 'KENYA', 'MALI',
       'GUAM', 'MACAU'], dtype=object)

In [57]:
## replace the values not in the country list (KEEP ADDING)
data_new["Country"]=data_new["Country"].replace('GUERNSEY, C.I','GUERNSEY').replace('(BLANK)'," ").replace('VIRGIN ISLANDS (BRITISH)','Virgin Islands (UK)').replace('JERSEY, C.I.','JERSEY').replace('ABU DHABI','UNITED ARAB EMIRATES').replace('TANZANIA, UNITED REP. OF','TANZANIA').replace("KOREA, DEM PEOPLE'S REP.","NORTH KOREA").replace('KOREA, REPUBLIC OF','SOUTH KOREA').replace("VIRGIN ISLANDS, U.S.","Virgin Islands (US)").replace('CANARIES ISLAND','SPAIN').replace('CONGO',"CONGO - BRAZZAVILLE").replace('DUBAI','UNITED ARAB EMIRATES').replace('EUROPEAN CENTRAL BANK-ECB',' ').replace('BRITISH INDIAN OCEAN TER.','BRITISH INDIAN OCEAN TERRITORY').replace('MOLDOVA (REPUBLIC OF)','MOLDOVA').replace('MACEDONIA, THE FORMER YU','MACEDONIA').replace('WORLD',' ').replace('THE STATE OF PALESTINE','PALESTINIAN TERRITORIES').replace("KYRGIZSTAN","KYRGYZSTAN")                                                
data_new["Country"].unique()

array(['CANADA', 'UNITED STATES', 'GUERNSEY', ' ', 'UNITED KINGDOM',
       'AUSTRALIA', 'GERMANY', 'LUXEMBOURG', 'SWITZERLAND', 'NETHERLANDS',
       '', 'FRANCE', 'CAYMAN ISLANDS', 'SPAIN', 'CHILE', 'BELARUS',
       'RUSSIA', 'SWEDEN', 'UNITED ARAB EMIRATES', 'NEW ZEALAND',
       'BELGIUM', 'BRAZIL', 'LIECHTENSTEIN', 'URUGUAY', 'HONG KONG',
       'IRELAND', 'MAURITIUS', 'COLOMBIA', 'ITALY', 'MEXICO', 'MALAYSIA',
       'BERMUDA', 'TURKEY', 'FINLAND', 'GIBRALTAR', 'CYPRUS', 'ARGENTINA',
       'CAMEROON', 'MOROCCO', 'NAMIBIA', 'INDIA', 'Virgin Islands (UK)',
       'MALTA', 'CHINA', 'ANDORRA', 'AUSTRIA', 'SINGAPORE', 'DENMARK',
       'JERSEY', 'BAHRAIN', 'SOUTH AFRICA', 'ISRAEL', 'ANGOLA',
       'ISLE OF MAN', 'ANGUILLA', 'SAUDI ARABIA', 'JAPAN', 'PERU',
       'ECUADOR', 'POLAND', 'CURACAO', 'HONDURAS', 'PORTUGAL',
       'GUATEMALA', 'MOZAMBIQUE', 'PHILIPPINES', 'ALBANIA', 'BOTSWANA',
       'GHANA', 'JAMAICA', 'NORTH KOREA', 'LITHUANIA', 'MONGOLIA',
       'TANZANIA', 'UGANDA', 'SENEGAL', 'PANAMA', 'ROMANIA', 'BAHAMAS',
       'HUNGARY', 'BULGARIA', 'TAIWAN', 'EGYPT', 'LIBYA', 'MAURITANIA',
       'MYANMAR', 'NIGERIA', 'OMAN', 'SRI LANKA', 'SWAZILAND',
       'TRINIDAD AND TOBAGO', 'TUNISIA', 'SOUTH KOREA',
       'Virgin Islands (US)', 'CONGO - BRAZZAVILLE', 'GREECE', 'CROATIA',
       'CZECH REPUBLIC', 'AFGHANISTAN', 'NORWAY', 'BARBADOS',
       'EQUATORIAL GUINEA', 'CAPE VERDE', 'KUWAIT', 'MONACO', 'QATAR',
       'MADAGASCAR', 'ESTONIA', 'VENEZUELA', 'KAZAKHSTAN', 'KYRGYZSTAN',
       'BRITISH INDIAN OCEAN TERRITORY', 'MARSHALL ISLAND', 'MOLDOVA',
       'RWANDA', 'MACEDONIA', 'UKRAINE', 'VIETNAM', 'INDONESIA',
       'AZERBAIJAN', 'LIBERIA', 'JORDAN', 'IVORY COAST', 'SIERRA LEONE',
       'COSTA RICA', 'PALESTINIAN TERRITORIES', 'PUERTO RICO',
       'CHRISTMAS ISLAND', 'FRENCH POLYNESIA', 'NEW CALEDONIA',
       'GUADELOUPE', 'DOMINICAN REPUBLIC', 'BOLIVIA', 'THAILAND',
       'GUINEA', 'SLOVAKIA', 'EL SALVADOR', 'SLOVENIA', 'BURKINA FASO',
       'CHAD', 'ALGERIA', 'ETHIOPIA', 'FIJI', 'ARUBA', 'BENIN', 'RÉUNION',
       'VIRGIN ISLANDS (US)', 'PAPUA NEW GUINEA', 'CUBA', 'MONTENEGRO',
       'VIRGIN ISLANDS (UK)', 'MARSHALL ISLANDS', 'PAKISTAN',
       'GUINEA-BISSAU', 'CAMBODIA', 'TOGO', 'NICARAGUA', 'ICELAND',
       'SERBIA', 'ARMENIA', 'CONGO - KINSHASA', 'NIGER', 'KENYA', 'MALI',
       'GUAM', 'MACAU'], dtype=object)

In [58]:
len(test1)

27668

In [127]:
#data_new.to_excel("country_cleaned_socgen_c5.xlsx")

# New Address Parsing (including Location 1)

In [61]:
#data_new=pd.read_excel("country_cleaned_socgen_c4.xlsx")
# country_name=pd.read_excel("")
data_new["Location 1 Country"].unique()
data_new["Location 1 Country"]=data_new["Location 1 Country"].replace(np.nan," ")

In [62]:
data_new["Location 1 Country"].unique()

array([' ', 'GBR', 'SGP', 'FRA', 'DEU', 'USA', 'MYS', 'LUX', 'BEL', 'JPN',
       'CHN', 'CHE', 'TWN', 'KOR', 'CAN', 'AUT', 'ESP', 'NLD', 'AUS',
       'FIN', 'ITA', 'GIB', 'HKG', 'PHL', 'ISR', 'NOR', 'IRL', 'SWE',
       'GGY', 'HUN', 'PRT', 'BRA', 'ARG', 'PYF', 'NCL', 'GLP', 'DNK',
       'GRC', 'TUR', 'POL', 'CZE', 'MAR', 'SEN', 'CIV', 'CMR', 'ZAF',
       'PRI', 'MEX', 'BMU', 'CRI', 'DOM', 'CYM', 'CUW', 'COL', 'PER',
       'CHL', 'BOL', 'SAU', 'BHR', 'IND', 'THA', 'IDN', 'NZL', 'ARE',
       'GIN', 'RUS', 'MCO', 'KWT', 'ROU', 'URY', 'SVK', 'SLV', 'IMN',
       'JOR', 'JEY', 'SVN', 'BHS', 'BFA', 'TCD', 'MDG', 'DZA', 'ETH',
       'EST', 'HND', 'FJI', 'TUN', 'VNM', 'TTO', 'GHA', 'ABW', 'BEN',
       'JAM', 'VIR', 'NGA', 'GTM', 'PNG', 'EGY', 'GNQ', 'CUB', 'AGO',
       'MLT', 'MDA', 'QAT', 'MNE', 'MRT', 'VGB', 'BLR', 'MKD', 'BRB',
       'COG', 'MOZ', 'GNB', 'MNG', 'ECU', 'CYP', 'KHM', 'PAN', 'MUS',
       'MHL', 'TGO', 'NIC', 'ISL', 'AIA', 'PAK', 'OMN', 'NAM', 'SRB',
       'ARM', 'AZE', 'COD', 'NER', 'KEN', 'MLI', 'GUM', 'MAC'],
      dtype=object)

In [63]:
# run when location1 is 3 iso


data_new["Location 1 Country"] = data_new["Location 1 Country"].str.upper()
country_list_location1=data_new["Location 1 Country"].to_list()

# 3_iso works
## all ran:2m
#country_list_location1=[]
for i in range(len(country_list_location1)):
    for m in range(len(country_name)):
        if country_list_location1[i]==country_name["3 Letter ISO"][m]:
            country_list_location1[i]=country_name["DDIQ Country Name"][m]
        else:
            country_list_location1[i]=country_list_location1[i]

data_new['Location 1 Country'] = country_list_location1
data_new['Location 1 Country']=data_new['Location 1 Country'].replace("nan",np.nan)
data_new["Location 1 Country"].unique()
#data_new["Country"].unique()

array([' ', 'United Kingdom', 'Singapore', 'France', 'Germany',
       'United States', 'Malaysia', 'Luxembourg', 'Belgium', 'Japan',
       'China', 'Switzerland', 'Taiwan', 'South Korea', 'Canada',
       'Austria', 'Spain', 'Netherlands', 'Australia', 'Finland', 'Italy',
       'Gibraltar', 'Hong Kong', 'Philippines', 'Israel', 'Norway',
       'Ireland', 'Sweden', 'Guernsey', 'Hungary', 'Portugal', 'Brazil',
       'Argentina', 'French Polynesia', 'New Caledonia', 'Guadeloupe',
       'Denmark', 'Greece', 'Turkey', 'Poland', 'Czech Republic',
       'Morocco', 'Senegal', 'Ivory Coast', 'Cameroon', 'South Africa',
       'Puerto Rico', 'Mexico', 'Bermuda', 'Costa Rica',
       'Dominican Republic', 'Cayman Islands', 'Curacao', 'Colombia',
       'Peru', 'Chile', 'Bolivia', 'Saudi Arabia', 'Bahrain', 'India',
       'Thailand', 'Indonesia', 'New Zealand', 'United Arab Emirates',
       'Guinea', 'Russia', 'Monaco', 'Kuwait', 'Romania', 'Uruguay',
       'Slovakia', 'El Salvador', 'Isle of Man', 'Jordan', 'Jersey',
       'Slovenia', 'Bahamas', 'Burkina Faso', 'Chad', 'Madagascar',
       'Algeria', 'Ethiopia', 'Estonia', 'Honduras', 'Fiji', 'Tunisia',
       'Vietnam', 'Trinidad and Tobago', 'Ghana', 'Aruba', 'Benin',
       'Jamaica', 'Virgin Islands (US)', 'Nigeria', 'Guatemala',
       'Papua New Guinea', 'Egypt', 'Equatorial Guinea', 'Cuba', 'Angola',
       'Malta', 'Moldova', 'Qatar', 'Montenegro', 'Mauritania',
       'Virgin Islands (UK)', 'Belarus', 'Macedonia', 'Barbados',
       'Congo - Brazzaville', 'Mozambique', 'Guinea-Bissau', 'Mongolia',
       'Ecuador', 'Cyprus', 'Cambodia', 'Panama', 'Mauritius',
       'Marshall Islands', 'Togo', 'Nicaragua', 'Iceland', 'Anguilla',
       'Pakistan', 'Oman', 'Namibia', 'Serbia', 'Armenia', 'Azerbaijan',
       'Congo - Kinshasa', 'Niger', 'Kenya', 'Mali', 'Guam', 'Macau'],
      dtype=object)

In [126]:
#data_new.to_excel("point_check.xlsx")
data_new[0:30]

,Address,City,Company Name *,Country,Location 1 Address,Location 1 City,Location 1 Country,Location 1 StateProv,Location 1 ZipPostal,StateProv,Submission Id,ZipPostal,identifier,concat
1,NaN,NaN,10036803 CANADA INC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-1,nan nan nan nan CANADA
2,NaN,NaN,"101 MERRIMAC HOLDINGS, LLC",UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-2,nan nan nan nan UNITED STATES
3,NaN,NaN,"101 MERRIMAC, INC",UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-3,nan nan nan nan UNITED STATES
4,NaN,NaN,"101 MERRIMAC, LLC",UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-4,nan nan nan nan UNITED STATES
5,NaN,WILMINGTON,1029 GEARY JV LLC,UNITED STATES,NaN,NaN,,NaN,NaN,DELAWARE,-9223372036854775808,19801,B-5,nan WILMINGTON DELAWARE 19801 UNITED STATES
6,NaN,WILMINGTON,1029 GEARY STREET PROPERTY LLC,UNITED STATES,NaN,NaN,,NaN,NaN,DELAWARE,-9223372036854775808,19801,B-6,nan WILMINGTON DELAWARE 19801 UNITED STATES
7,NaN,TORONTO,10614408 CANADA LIMITED,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,ON M5H 3Y2,B-7,nan TORONTO nan ON M5H 3Y2 CANADA
8,NaN,NaN,10814253 CANADA INC,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-8,nan nan nan nan UNITED STATES
9,NaN,NaN,1102952 B.C. UNLIMITED LIABILITY COMPANY,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-9,nan nan nan nan CANADA
10,NaN,LEVIS,1185-9576 QUEBEC INC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,G6V8V6,B-10,nan LEVIS nan G6V8V6 CANADA
11,NaN,NaN,1212770 BC LTD,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-11,nan nan nan nan CANADA
12,NaN,DOVER,1625 EYE STREET GP LLC,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,19904,B-12,nan DOVER nan 19904 UNITED STATES
13,NaN,DOVER,1625 EYE STREET HOLDINGS LLC,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,19904,B-13,nan DOVER nan 19904 UNITED STATES
14,NaN,GUERNSEY,1625 EYE STREET INVESTMENTS LIMITED,GUERNSEY,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,GY1 3NF,B-14,nan GUERNSEY nan GY1 3NF GUERNSEY
15,NaN,DOVER,1625 EYE STREET L.P,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,19904,B-15,nan DOVER nan 19904 UNITED STATES
16,NaN,INDIANAPOLIS,16 TECH COMMUNITY CORPORATION,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-16,nan INDIANAPOLIS nan nan UNITED STATES
17,NaN,TORONTO,1706065 ALBERTA ULC,CANADA,NaN,NaN,,NaN,NaN,ON,-9223372036854775808,MJ5 2T3,B-17,nan TORONTO ON MJ5 2T3 CANADA
18,NaN,NaN,1706065 ALBERTA ULC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-18,nan nan nan nan CANADA
19,NaN,,1706065 CANADA ULC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,,B-19,nan nan CANADA
20,NaN,,1706065 CANADA ULC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,,B-20,nan nan CANADA
21,NaN,NaN,171263 CANADA INC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-21,nan nan nan nan CANADA
22,NaN,NaN,1799101 ONTARIO INC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-22,nan nan nan nan CANADA
23,NaN,WILMINGTON,17 DECATUR JV LLC,UNITED STATES,NaN,NaN,,NaN,NaN,DELAWARE,-9223372036854775808,19801,B-23,nan WILMINGTON DELAWARE 19801 UNITED STATES
24,NaN,WILMINGTON,17 DECATUR STREET PROPERTY LLC,UNITED STATES,NaN,NaN,,NaN,NaN,DELAWARE,-9223372036854775808,19801,B-24,nan WILMINGTON DELAWARE 19801 UNITED STATES
25,NaN,NaN,17 H20PARTNERS,,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-25,nan nan nan nan
26,NaN,NaN,180 MAIDEN LANE JV LLC,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-26,nan nan nan nan UNITED STATES
27,NaN,NaN,1867 INFRASTRUCTURE HOLDINGS INC,,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-27,nan nan nan nan
28,NaN,NaN,1867 NA30 HOLDING INC,,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-28,nan nan nan nan
29,NaN,NaN,1867 NOUVELLE AUTOROUTE 30 INC,,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-29,nan nan nan nan
30,NaN,NaN,1900 HOLDINGS CORPORATION,UNITED KINGDOM,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-30,nan nan nan nan UNITED KINGDOM

In [65]:
## added: company name upper case; country upper case; "NAN" ; Fix ZIP, CITY and STATE
data_new["Company Name *"]=data_new["Company Name *"].str.upper()
data_new["Address"]=data_new["Address"].str.upper()
data_new["City"]=data_new["City"].str.upper()
data_new["Location 1 Address"]=data_new["Location 1 Address"].str.upper()
data_new["Location 1 City"]=data_new["Location 1 City"].str.upper()
data_new["StateProv"]=data_new["StateProv"].str.upper()
data_new["Location 1 StateProv"]=data_new["Location 1 StateProv"].str.upper()
data_new["ZipPostal"]=data_new["ZipPostal"].str.upper()
data_new["Location 1 ZipPostal"]=data_new["Location 1 ZipPostal"].str.upper()


data_new["Location 1 Country"]=data_new["Location 1 Country"].str.upper()
data_new["Location 1 Country"]=data_new["Location 1 Country"].replace("NAN"," ")
data_new["Country"]=data_new["Country"].replace("NAN"," ")
data_new["City"]=data_new["City"].replace("0",np.nan).replace("n..a",np.nan).replace("Na",np.nan).replace("N/a",np.nan).replace("n/A",np.nan)                                 
data_new["ZipPostal"]=data_new["ZipPostal"].replace("0",np.nan).replace("n..a",np.nan).replace("Na",np.nan).replace("N/a",np.nan).replace("n/A",np.nan)
data_new["StateProv"]=data_new["StateProv"].replace("0",np.nan)
data_new["Location 1 Country"].unique()
#data_new["City"].unique()
data_new.to_excel("point_check2.xlsx")

In [66]:
new_df=data_new[["Company Name *","Location 1 Address","Location 1 City","Location 1 StateProv","Location 1 ZipPostal","Location 1 Country","Submission Id","identifier"]]

new_df=new_df.rename(columns={"Location 1 Address":"Address",
                              "Location 1 City":"City",
                              "Location 1 StateProv":"StateProv", 
                              "Location 1 ZipPostal":"ZipPostal",
                             "Location 1 Country":"Country"})
new_df["s_id"]=0

old_df=data_new[["Company Name *","Address","City","StateProv","ZipPostal","Country","Submission Id","identifier"]]

old_df["s_id"]=1
concat=pd.concat([new_df,old_df], join="outer")

/Users/ljiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [67]:
# concat["Submission Id"]=concat["Submission Id"].astype(str).replace("nan","99999999999")
# concat["Submission Id"]=concat["Submission Id"].astype(int)
# concat

In [68]:
#concat.to_excel("concat.xlsx")

In [69]:
# sort on address, submission id and name (name,subID,country,s_id)
concat = concat.sort_values(['Company Name *','Submission Id',"Country",'s_id'], ascending=[True,True,False,False])

h=concat.groupby(['Company Name *']).agg({"identifier":"unique"})
#concate the data and deduplicate
concat["concat"] = concat['Address'].map(str) +' ' + concat['City'].map(str) +' ' + concat['StateProv'].map(str)+' ' + concat['ZipPostal'].map(str)+' '+concat['Country'].map(str)
data_dedupli=concat.drop_duplicates(subset=['Company Name *','concat'], keep="first")

#data_dedupli = data_dedupli.sort_values(['Country','Company Name *'], ascending=[False, True])

g=data_dedupli.groupby(['Company Name *']).agg({'Address':lambda x: list(x),
                                              'City':lambda x: list(x),
                                             'StateProv':lambda x: list(x),
                                             'ZipPostal':lambda x: list(x),
                                             "Country":lambda x: list(x)})



## change into workbench format: need to include city, state, country name change
h.reset_index(inplace=True)
g.reset_index(inplace=True)

In [125]:
#data_dedupli.to_excel("duplicates_check.xlsx")
g[0:30]

,Company Name *,Address,City,StateProv,ZipPostal,Country
0,(INTECH/5132)NOMURA ASSET MANAGEMENT CO LTD-TH...,[2-2-2 OTEMACHI],[TOKYO],[TOKYO],[100-0004],[JAPAN]
1,"(INTECH/5140)NIKKO ASSET MANAGEMENT CO, LTD-TH...","[2-11-3, HAMAMATSUCHO]",[TOKYO],[TOKYO],[105-8579],[JAPAN]
2,"(INTECH/5142)SUMITOMO MITSUI TRUST BANK, LTD.-...",[1-8-11 HARUMI],[TOKYO],[TOKYO],[104-6107],[JAPAN]
3,"(INTECH/5154)NIKKO ASSET MANAGEMENT CO, LTD-TH...","[2-11-3, HAMAMATSUCHO]",[TOKYO],[TOKYO],[105-8579],[JAPAN]
4,"(INTECH/I5157)SUMITOMO MITSUI TRUST BANK, LTD-...","[2-11-3, HAMAMATSUCHO]",[TOKYO],[nan],[105-8579],[JAPAN]
5,075A - PHS ITP DOMESTIC FI,[1209 ORANGE ST],[WILMINGTON],[DE],[19801],[UNITED STATES]
6,0890696 B.C. LTD,[2300 - 1055 DUNSMUIR STREET],[VANCOUVER],[BC],[BC V7X1L4],[CANADA]
7,1-3 YEAR CREDIT BOND INDEX NON-LENDABLE FUND,[400 HOWARD STREET],[SAN FRANCISCO],[CA],[94105],[UNITED STATES]
8,100 WALNUT LLC,[122 QUENTIN AVE],[NEW BRUNSWICK],[NJ],[08901],[UNITED STATES]
9,10036803 CANADA INC,[nan],[nan],[nan],[nan],[CANADA]
10,"101 MERRIMAC HOLDINGS, LLC",[nan],[nan],[nan],[nan],[UNITED STATES]
11,"101 MERRIMAC OWNER, LLC",[1209 ORANGE ST],[WILMINGTON],[DE],[19801],[UNITED STATES]
12,"101 MERRIMAC, INC",[nan],[nan],[nan],[nan],[UNITED STATES]
13,"101 MERRIMAC, LLC",[nan],[nan],[nan],[nan],[UNITED STATES]
14,1029 GEARY JV LLC,[nan],[WILMINGTON],[DELAWARE],[19801],[UNITED STATES]
15,1029 GEARY STREET PROPERTY LLC,[nan],[WILMINGTON],[DELAWARE],[19801],[UNITED STATES]
16,10614408 CANADA LIMITED,[nan],[TORONTO],[nan],[ON M5H 3Y2],[CANADA]
17,10618667 CANADA INC,[1000 DE LA GAUCHETIERE WEST],[MONTREAL QC],[QC],[H3B 5A7],[CANADA]
18,1069024 ONTARIO LIMITED,[2 QUEEN STREET EAST],[TORONTO],[ON],[M5C 3G5],[CANADA]
19,10814253 CANADA INC,[nan],[nan],[nan],[nan],[UNITED STATES]
20,1102952 B.C. UNLIMITED LIABILITY COMPANY,[nan],[nan],[nan],[nan],[CANADA]
21,1185-9576 QUEBEC INC,[nan],[LEVIS],[nan],[G6V8V6],[CANADA]
22,1199SEIU HEALTH CARE EMPLOYEES PENSION FUND,[251 LITTLE FALLS DRIVE],[WILMINGTON],[DE],[19808],[UNITED STATES]
23,1212770 BC LTD,[nan],[nan],[nan],[nan],[CANADA]
24,1397225 ONTARIO LIMITED,[5650 YONGE STREET],[TORONTO],[ON],[M2M 4H5],[CANADA]
25,145 SPRING STREET PARTNERS LLC,[160 GREENTREE DR],[DOVER],[DE],[19904],[UNITED STATES]
26,16 TECH COMMUNITY CORPORATION,[nan],[INDIANAPOLIS],[nan],[nan],[UNITED STATES]
27,"161 N CLARK OWNER, LLC",[1209 ORANGE ST],[WILMINGTON],[DE],[19801],[UNITED STATES]
28,1625 EYE STREET GP LLC,[nan],[DOVER],[nan],[19904],[UNITED STATES]
29,1625 EYE STREET HOLDINGS LLC,[nan],[DOVER],[nan],[19904],[UNITED STATES]

In [71]:
#data_new

In [72]:
address=g[["Company Name *","Address"]]
address=address.Address.apply(pd.Series).merge(address, left_index = True, right_index = True).drop(["Address"],axis=1)
address_final=address[["Company Name *",0,1,2,3,4,5,6,7,8,9,10]]
address_final=address_final.rename(columns={0: "Address",1:"Location 1 Address",2:"Location 2 Address",
                              3:"Location 3 Address", 4:"Location 4 Address", 5:"Location 5 Address",
                              6:"Location 6 Address",7:"Location 7 Address",8:"Location 8 Address",
                              9:"Location 9 Address",10:"Location 10 Address"})



address_final=address_final.merge(g,how='inner', left_on="Company Name *", right_on="Company Name *")

#address_final

In [73]:
## City code
city_code=g[["Company Name *","City"]]
city_code=city_code.City.apply(pd.Series).merge(city_code, left_index = True, right_index = True)
city_code=city_code[["Company Name *",0,1,2,3,4,5,6,7,8,9,10]].rename(columns={0: "City",1:"Location 1 City",
                                                                         2:"Location 2 City",
                              3:"Location 3 City", 4:"Location 4 City", 5:"Location 5 City",
                              6:"Location 6 City",7:"Location 7 City",8:"Location 8 City",
                              9:"Location 9 City",10:"Location 10 City"})

city_code=city_code.merge(g,how='inner', left_on="Company Name *", right_on="Company Name *")
#,6,7,8,9,10   
# city_code

In [74]:
## StateProv
#["Company Name *",0,1,2,3,4,5,6,7,8,9,10]]
#,6,7
StateProv_code=g[["Company Name *","StateProv"]]
StateProv_code=StateProv_code.StateProv.apply(pd.Series).merge(StateProv_code, left_index = True, right_index = True)
StateProv_code=StateProv_code[["Company Name *",0,1,2,3,4,5,6,7,8,9,10]].rename(columns={0: "StateProv",1:"Location 1 StateProv",
                                                                          2:"Location 2 StateProv",
                              3:"Location 3 StateProv", 4:"Location 4 StateProv", 5:"Location 5 StateProv",
                              6:"Location 6 StateProv",7:"Location 7 StateProv",8:"Location 8 StateProv",
                                9:"Location 9 StateProv",10:"Location 10 StateProv"                                           })

StateProv_code=StateProv_code.merge(g,how='inner', left_on="Company Name *", right_on="Company Name *")
# StateProv_code

In [75]:
## zip code
#,6,7,8,9,10
zip_code=g[["Company Name *","ZipPostal"]]
zip_code=zip_code.ZipPostal.apply(pd.Series).merge(zip_code, left_index = True, right_index = True)
zip_code=zip_code[["Company Name *",0,1,2,3,4,5,6,7,8,9,10]].rename(columns={0: "ZipPostal",1:"Location 1 ZipPostal",
                                                                          2:"Location 2 ZipPostal",
                              3:"Location 3 ZipPostal", 4:"Location 4 ZipPostal", 5:"Location 5 ZipPostal",
                              6:"Location 6 ZipPostal",7:"Location 7 ZipPostal",8:"Location 8 ZipPostal",
                              9:"Location 9 ZipPostal",10:"Location 10 ZipPostal"})
zip_code=zip_code.merge(g,how='inner', left_on="Company Name *", right_on="Company Name *")
# zip_code

In [76]:
## country code
#,6,7,8,9,10
c_code=g[["Company Name *","Country"]]
c_code=c_code.Country.apply(pd.Series).merge(c_code, left_index = True, right_index = True)
c_code=c_code[["Company Name *",0,1,2,3,4,5,6,7,8,9,10]].rename(columns={0: "Country",1:"Location 1 Country",
                                                                          2:"Location 2 Country",
                              3:"Location 3 Country", 4:"Location 4 Country", 5:"Location 5 Country",
                              6:"Location 6 Country",7:"Location 7 Country",8:"Location 8 Country",
                              9:"Location 9 Country", 10:"Location 10 Country"
                                                             })
c_code=c_code.merge(g,how='inner', left_on="Company Name *", right_on="Company Name *")
# c_code

In [77]:
data_frames4 = [address_final, city_code, StateProv_code,zip_code,c_code]
df_merged4 = reduce(lambda  left,right: pd.merge(left,right,on=['Company Name *'],
                                            how='outer'), data_frames4)
df_merged4=df_merged4.rename(columns={"Address_x": "Address",
                          "City_y":"City",
                          "StateProv_y":"StateProv",
                          "ZipPostal_y":"ZipPostal", 
                          "Country_y":"Country"})

In [78]:
df_merged4.to_excel("address_qa778.xlsx")

In [124]:
df_merged4[0:30]

,Company Name *,Address,Location 1 Address,Location 2 Address,Location 3 Address,Location 4 Address,Location 5 Address,Location 6 Address,Location 7 Address,Location 8 Address,...,Location 6 Country,Location 7 Country,Location 8 Country,Location 9 Country,Location 10 Country,Address_y,City,StateProv,ZipPostal,Country_y_y
0,(INTECH/5132)NOMURA ASSET MANAGEMENT CO LTD-TH...,250 S. AUSTRALIAN AVENUE,2-2-2 OTEMACHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[250 S. AUSTRALIAN AVENUE, 2-2-2 OTEMACHI]","[WEST PALM BEACH, TOKYO]","[FL, TOKYO]","[33401, 100-0004]","[UNITED STATES, JAPAN]"
1,"(INTECH/5140)NIKKO ASSET MANAGEMENT CO, LTD-TH...",250 S. AUSTRALIAN AVENUE,"2-11-3, HAMAMATSUCHO",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[250 S. AUSTRALIAN AVENUE, 2-11-3, HAMAMATSUCHO]","[WEST PALM BEACH, TOKYO]","[FL, TOKYO]","[33401, 105-8579]","[UNITED STATES, JAPAN]"
2,"(INTECH/5142)SUMITOMO MITSUI TRUST BANK, LTD.-...",250 S. AUSTRALIAN AVENUE,1-8-11 HARUMI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[250 S. AUSTRALIAN AVENUE, 1-8-11 HARUMI]","[WEST PALM BEACH, TOKYO]","[FL, TOKYO]","[33401, 104-6107]","[UNITED STATES, JAPAN]"
3,"(INTECH/5154)NIKKO ASSET MANAGEMENT CO, LTD-TH...",250 S. AUSTRALIAN AVENUE,"2-11-3, HAMAMATSUCHO",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[250 S. AUSTRALIAN AVENUE, 2-11-3, HAMAMATSUCHO]","[WEST PALM BEACH, TOKYO]","[FL, TOKYO]","[33401, 105-8579]","[UNITED STATES, JAPAN]"
4,"(INTECH/I5157)SUMITOMO MITSUI TRUST BANK, LTD-...",250 S. AUSTRALIAN AVENUE,"2-11-3, HAMAMATSUCHO",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[250 S. AUSTRALIAN AVENUE, 2-11-3, HAMAMATSUCHO]","[WEST PALM BEACH, TOKYO]","[FL, nan]","[33401, 105-8579]","[UNITED STATES, JAPAN]"
5,075A - PHS ITP DOMESTIC FI,1209 ORANGE ST,2 SEAPORT LANE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[1209 ORANGE ST, 2 SEAPORT LANE]","[WILMINGTON, BOSTON]","[DE, MA]","[19801, 02210]","[UNITED STATES, UNITED STATES]"
6,0890696 B.C. LTD,2300 - 1055 DUNSMUIR STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,[2300 - 1055 DUNSMUIR STREET],[VANCOUVER],[BC],[BC V7X1L4],[CANADA]
7,1-3 YEAR CREDIT BOND INDEX NON-LENDABLE FUND,400 HOWARD STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,[400 HOWARD STREET],[SAN FRANCISCO],[CA],[94105],[UNITED STATES]
8,100 WALNUT LLC,122 QUENTIN AVE,20 COMMERCE DR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[122 QUENTIN AVE, 20 COMMERCE DR]","[NEW BRUNSWICK, CRANFORD]","[NJ, NJ]","[08901, 07016]","[UNITED STATES, UNITED STATES]"
9,10036803 CANADA INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[CANADA, ]"
10,"101 MERRIMAC HOLDINGS, LLC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[UNITED STATES, ]"
11,"101 MERRIMAC OWNER, LLC",1209 ORANGE ST,"234 CLARENDON STREET,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[1209 ORANGE ST, 234 CLARENDON STREET,]","[WILMINGTON, BOSTON]","[DE, MA]","[19801, 02116]","[UNITED STATES, UNITED STATES]"
12,"101 MERRIMAC, INC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[UNITED STATES, ]"
13,"101 MERRIMAC, LLC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[UNITED STATES, ]"
14,1029 GEARY JV LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[WILMINGTON, nan]","[DELAWARE, nan]","[19801, nan]","[UNITED STATES, ]"
15,1029 GEARY STREET PROPERTY LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[WILMINGTON, nan]","[DELAWARE, nan]","[19801, nan]","[UNITED STATES, ]"
16,10614408 CANADA LIMITED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[TORONTO, nan]","[nan, nan]","[ON M5H 3Y2, nan]","[CANADA, ]"
17,10618667 CANADA INC,1000 DE LA GAUCHETIERE WEST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,[1000 DE LA GAUCHETIERE WEST],[MONTREAL QC],[QC],[H3B 5A7],[CANADA]
18,1069024 ONTARIO LIMITED,2 QUEEN STREET EAST,595 BURRARD STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[2 QUEEN STREET EAST, 595 BURRARD STREET]","[TORONTO, VANCOUVER]","[ON, BC]","[M5C 3G5, V7X 1J1]","[CANADA, CANADA]"
19,10814253 CANADA INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[UNITED STATES, ]"
20,1102952 B.C. UNLIMITED LIABILITY COMPANY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[CANADA, ]"
21,1185-9576 QUEBEC INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[LEVIS, nan]","[nan, nan]","[G6V8V6, nan]","[CANADA, ]"
22,1199SEIU HEALTH CARE EMPLOYEES PENSION FUND,251 LITTLE FALLS DRIVE,251 LITTLE FALLS DRIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[251 LITTLE FALLS DRIVE, 251 LITTLE FALLS DRIVE]","[WILMINGTON, LOS ANGELES]","[DE, CA]","[19808, 19808]","[UNITED STATES, UNITED STATES]"
23,1212770 BC LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[CANADA, ]"
24,1397225 ONTARIO LIMITED,5650 YONGE STREET,5650 YONGE STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[5650 YONGE STREET, 5650 YONGE STREET]","[TORONTO, TORONTO]","[ON, nan]","[M2M 4H5, M2M 4H5]","[CANADA, CANADA]"
25,145 SPRING STREET PARTNERS LLC,160 GREENTREE DR,28 LIBERTY STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[160 GREENTREE DR, 28 LIBERTY STREET]","[DOVER, NEW YORK]","[DE, NY]","[19904, 10005]","[UNITED STATES, UNITED STATES]"
26,16 TECH COMMUNITY CORPORATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[INDIANAPOLIS, nan]","[nan, nan]","[nan, nan]","[UNITED STATES, ]"
27,"161 N CLARK OWNER, LLC",1209 ORANGE ST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,[1209 ORANGE ST],[WILMINGTON],[DE],[19801],[UNITED STATES]
28,1625 EYE STREET GP LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[DOVER, nan]","[nan, nan]","[19904, nan]","[UNITED STATES, ]"
29,1625 EYE STREET HOLDINGS LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"[nan, nan]","[DOVER, nan]","[nan, nan]","[19904, nan]","[UNITED STATES, ]"

# submission ID

# Start NEW SUB

In [80]:
#data_new=pd.read_excel("country_cleaned_socgen_c4.xlsx")
#data_new=data.copy()

In [81]:
# ## format clean run for the submission ID takes 30m to run 
# for i in range(len(data_new)):
#     if data_new["Submission Id"][i]!=np.nan:
#         data_new["Submission Id"][i]=data_new["Submission Id"][i].astype(int)

In [123]:
data_new[0:30]

,Address,City,Company Name *,Country,Location 1 Address,Location 1 City,Location 1 Country,Location 1 StateProv,Location 1 ZipPostal,StateProv,Submission Id,ZipPostal,identifier,concat
1,NaN,NaN,10036803 CANADA INC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-1,nan nan nan nan CANADA
2,NaN,NaN,"101 MERRIMAC HOLDINGS, LLC",UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-2,nan nan nan nan UNITED STATES
3,NaN,NaN,"101 MERRIMAC, INC",UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-3,nan nan nan nan UNITED STATES
4,NaN,NaN,"101 MERRIMAC, LLC",UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-4,nan nan nan nan UNITED STATES
5,NaN,WILMINGTON,1029 GEARY JV LLC,UNITED STATES,NaN,NaN,,NaN,NaN,DELAWARE,-9223372036854775808,19801,B-5,nan WILMINGTON DELAWARE 19801 UNITED STATES
6,NaN,WILMINGTON,1029 GEARY STREET PROPERTY LLC,UNITED STATES,NaN,NaN,,NaN,NaN,DELAWARE,-9223372036854775808,19801,B-6,nan WILMINGTON DELAWARE 19801 UNITED STATES
7,NaN,TORONTO,10614408 CANADA LIMITED,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,ON M5H 3Y2,B-7,nan TORONTO nan ON M5H 3Y2 CANADA
8,NaN,NaN,10814253 CANADA INC,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-8,nan nan nan nan UNITED STATES
9,NaN,NaN,1102952 B.C. UNLIMITED LIABILITY COMPANY,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-9,nan nan nan nan CANADA
10,NaN,LEVIS,1185-9576 QUEBEC INC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,G6V8V6,B-10,nan LEVIS nan G6V8V6 CANADA
11,NaN,NaN,1212770 BC LTD,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-11,nan nan nan nan CANADA
12,NaN,DOVER,1625 EYE STREET GP LLC,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,19904,B-12,nan DOVER nan 19904 UNITED STATES
13,NaN,DOVER,1625 EYE STREET HOLDINGS LLC,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,19904,B-13,nan DOVER nan 19904 UNITED STATES
14,NaN,GUERNSEY,1625 EYE STREET INVESTMENTS LIMITED,GUERNSEY,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,GY1 3NF,B-14,nan GUERNSEY nan GY1 3NF GUERNSEY
15,NaN,DOVER,1625 EYE STREET L.P,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,19904,B-15,nan DOVER nan 19904 UNITED STATES
16,NaN,INDIANAPOLIS,16 TECH COMMUNITY CORPORATION,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-16,nan INDIANAPOLIS nan nan UNITED STATES
17,NaN,TORONTO,1706065 ALBERTA ULC,CANADA,NaN,NaN,,NaN,NaN,ON,-9223372036854775808,MJ5 2T3,B-17,nan TORONTO ON MJ5 2T3 CANADA
18,NaN,NaN,1706065 ALBERTA ULC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-18,nan nan nan nan CANADA
19,NaN,,1706065 CANADA ULC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,,B-19,nan nan CANADA
20,NaN,,1706065 CANADA ULC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,,B-20,nan nan CANADA
21,NaN,NaN,171263 CANADA INC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-21,nan nan nan nan CANADA
22,NaN,NaN,1799101 ONTARIO INC,CANADA,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-22,nan nan nan nan CANADA
23,NaN,WILMINGTON,17 DECATUR JV LLC,UNITED STATES,NaN,NaN,,NaN,NaN,DELAWARE,-9223372036854775808,19801,B-23,nan WILMINGTON DELAWARE 19801 UNITED STATES
24,NaN,WILMINGTON,17 DECATUR STREET PROPERTY LLC,UNITED STATES,NaN,NaN,,NaN,NaN,DELAWARE,-9223372036854775808,19801,B-24,nan WILMINGTON DELAWARE 19801 UNITED STATES
25,NaN,NaN,17 H20PARTNERS,,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-25,nan nan nan nan
26,NaN,NaN,180 MAIDEN LANE JV LLC,UNITED STATES,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-26,nan nan nan nan UNITED STATES
27,NaN,NaN,1867 INFRASTRUCTURE HOLDINGS INC,,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-27,nan nan nan nan
28,NaN,NaN,1867 NA30 HOLDING INC,,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-28,nan nan nan nan
29,NaN,NaN,1867 NOUVELLE AUTOROUTE 30 INC,,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-29,nan nan nan nan
30,NaN,NaN,1900 HOLDINGS CORPORATION,UNITED KINGDOM,NaN,NaN,,NaN,NaN,NaN,-9223372036854775808,NaN,B-30,nan nan nan nan UNITED KINGDOM

In [83]:
# data_new["Submission Id"]=data_new["Submission Id"].astype(str)

In [84]:
# data_new["Submission Id"]=data_new["Submission Id"].replace('nan',"-9223372036854775808")

In [85]:
# data_new["Submission Id"]=data_new["Submission Id"].astype(int)
# #data_new["Submission Id"][1]

In [86]:
data_new['Submission Id'] = data_new['Submission Id'].fillna(-9223372036854775808).astype(int)

In [87]:
data_new["Submission Id"]

1       -9223372036854775808
2       -9223372036854775808
3       -9223372036854775808
4       -9223372036854775808
5       -9223372036854775808
6       -9223372036854775808
7       -9223372036854775808
8       -9223372036854775808
9       -9223372036854775808
10      -9223372036854775808
11      -9223372036854775808
12      -9223372036854775808
13      -9223372036854775808
14      -9223372036854775808
15      -9223372036854775808
16      -9223372036854775808
17      -9223372036854775808
18      -9223372036854775808
19      -9223372036854775808
20      -9223372036854775808
21      -9223372036854775808
22      -9223372036854775808
23      -9223372036854775808
24      -9223372036854775808
25      -9223372036854775808
26      -9223372036854775808
27      -9223372036854775808
28      -9223372036854775808
29      -9223372036854775808
30      -9223372036854775808
                ...
11759              518786536
11760              518964342
11761              518964396
11762              519126051
11763              519127849
11764              519623419
11765              520100638
11766              520100655
11767              520100665
11768              520100675
11769              520100698
11770              520743463
11771              521045841
11772              521550456
11773              521691370
11774              521691385
11775              522049183
11776              522208350
11777              522345249
11778              524478807
11779              524639196
11780              524639250
11781              526559701
11782              526559702
11783              526559703
11784              526559704
11785              526559706
11786              526559707
11787              526559708
11788              526597764
Name: Submission Id, Length: 27668, dtype: int64

In [88]:
data_new["Company Name *"]=data_new["Company Name *"].str.upper()
group_id=data_new.groupby(['Company Name *']).agg({'Submission Id':'unique'})
group_id=group_id.rename(columns={'Submission Id':'old_id'})
group_id.reset_index(inplace=True)
#group_id
print("DONE")

DONE

In [89]:
## nested list for submission_id
old_id=group_id['old_id'].to_list()
lst_id=[]
for i in range(len(old_id)):
    lst_id.append(old_id[i].tolist())
lst_id

[[72553409],
 [72553413],
 [72837076],
 [72553411],
 [72553403],
 [60030172],
 [363418982],
 [267373735],
 [507135948],
 [-9223372036854775808],
 [-9223372036854775808],
 [479233120],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [323561654],
 [180437030],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [74152393],
 [-9223372036854775808],
 [226011210],
 [456378776],
 [-9223372036854775808],
 [365521004],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [87875276],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [273381085],
 [-9223372036854775808],
 [-9223372036854775808],
 [229331],
 [493337937],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [76128117],
 [3769711],
 [-9223372036854775808],
 [-9223372036854775808],
 [332506922],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [469403036],
 [250560961],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [338615996],
 [-9223372036854775808, 284236603],
 [355730209],
 [273502858],
 [-9223372036854775808],
 [-9223372036854775808],
 [449640165],
 [-9223372036854775808],
 [-9223372036854775808, 306794122],
 [448834705],
 [-9223372036854775808],
 [-9223372036854775808],
 [218558725],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [13140944],
 [64185362],
 [-9223372036854775808],
 [4719724],
 [-9223372036854775808],
 [-9223372036854775808],
 [273502646],
 [238210762],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 32470],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [240484060],
 [25790],
 [22748679],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [182627274],
 [182627142],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 298653311],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [273502814],
 [-9223372036854775808],
 [466490745],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 486658474],
 [382761734],
 [382761748],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 401174931],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [76199094],
 [-9223372036854775808],
 [332197874],
 [-9223372036854775808],
 [-9223372036854775808, 11008248],
 [-9223372036854775808],
 [-9223372036854775808],
 [138912780],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [438125436],
 [450404031],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [182627221],
 [182627493],
 [28347583],
 [-9223372036854775808],
 [-9223372036854775808],
 [507136380],
 [-9223372036854775808],
 [-9223372036854775808],
 [188907074],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [142721475],
 [-9223372036854775808],
 [-9223372036854775808],
 [367188965],
 [28839],
 [-9223372036854775808],
 [-9223372036854775808],
 [73210688],
 [311349232],
 [476197486],
 [352376326],
 [49312242],
 [67960971],
 [359321913],
 [-9223372036854775808],
 [-9223372036854775808],
 [65953450],
 [-9223372036854775808],
 [8377506],
 [-9223372036854775808],
 [178715015],
 [289855552],
 [-9223372036854775808],
 [-9223372036854775808, 22076202],
 [223328584],
 [-9223372036854775808],
 [178984913],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [1536307],
 [-9223372036854775808],
 [-9223372036854775808],
 [9310439],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [1717092],
 [-9223372036854775808],
 [2313482],
 [1877036],
 [2480513],
 [2641979],
 [15603970],
 [363578704],
 [97548217],
 [14848],
 [54250542],
 [88822945],
 [47671286],
 [383752292],
 [877],
 [11714783],
 [11363389],
 [1639639],
 [361407876],
 [1850758],
 [76739525],
 [-9223372036854775808, 189175],
 [430225875],
 [88821887],
 [15603946],
 [200524404],
 [3520998],
 [14851],
 [54300907],
 [75959327],
 [11484327],
 [2641974],
 [1617707],
 [423325651],
 [424362461],
 [204511010],
 [-9223372036854775808],
 [11363386],
 [34141095],
 [2641985],
 [430666695],
 [12486033],
 [1729257],
 [49196905],
 [15603958],
 [20111042],
 [48039241],
 [56671507],
 [74996191],
 [380886749],
 [48437886],
 [-9223372036854775808, 46451767],
 [48804913],
 [48784459],
 [48379371],
 [48437885],
 [74838735],
 [121824605],
 [48379373],
 [-9223372036854775808, 47096571],
 [48385751],
 [48804909],
 [47362693],
 [-9223372036854775808],
 [394708658],
 [2003864],
 [-9223372036854775808],
 [-9223372036854775808],
 [26553],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 211343],
 [44319526],
 [140606747],
 [24189],
 [4979427],
 [-9223372036854775808],
 [174005],
 [242655076],
 [-9223372036854775808],
 [375010949],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [405622937],
 [251375404],
 [-9223372036854775808],
 [-9223372036854775808, 11169622],
 [12101244],
 [16589988],
 [-9223372036854775808],
 [27844],
 [170984],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [7195],
 [12745307],
 [252647853],
 [148781260],
 [-9223372036854775808],
 [2745379],
 [-9223372036854775808],
 [-9223372036854775808, 31005],
 [81745624],
 [-9223372036854775808],
 [-9223372036854775808],
 [75500879],
 [458379048],
 [-9223372036854775808],
 [-9223372036854775808],
 [10781],
 [-9223372036854775808],
 [348148304],
 [162913108],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [13543449],
 [87445046],
 [228262],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [1213114],
 [-9223372036854775808],
 [74550071],
 [281194690],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [44877589],
 [22223617],
 [177908818],
 [-9223372036854775808],
 [-9223372036854775808],
 [405490569],
 [207198612],
 [-9223372036854775808],
 [2855980],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [73208578],
 [-9223372036854775808],
 [-9223372036854775808],
 [10211621],
 [101199600],
 [-9223372036854775808],
 [-9223372036854775808],
 [6357942],
 [90845670],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [1382436],
 [-9223372036854775808],
 [2966051],
 [231443179],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [2372818],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [267267852],
 [229083918],
 [-9223372036854775808],
 [87124902],
 [1267538],
 [360658510],
 [143704869],
 [169567182],
 [-9223372036854775808],
 [11068050],
 [7632091],
 [246587124],
 [501540788],
 [-9223372036854775808],
 [-9223372036854775808],
 [4116675],
 [28863],
 [-9223372036854775808],
 [-9223372036854775808],
 [13333392],
 [1563540],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 20294],
 [-9223372036854775808],
 [-9223372036854775808],
 [373153745],
 [-9223372036854775808],
 [-9223372036854775808, 13340532],
 [-9223372036854775808],
 [1957891],
 [-9223372036854775808],
 [-9223372036854775808],
 [2114806],
 [27888424],
 [344145154],
 [396671043],
 [171715065],
 [55380786],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [80305357],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 2375188],
 [13318785],
 [141523230],
 [244979688],
 [245421659],
 [244979674],
 [244979672],
 [-9223372036854775808, 83273694],
 [21884911],
 [-9223372036854775808],
 [171957091],
 [95341367],
 [-9223372036854775808],
 [-9223372036854775808],
 [120768791],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [214303237],
 [226701481],
 [-9223372036854775808],
 [61243433],
 [-9223372036854775808],
 [4175967],
 [4172667],
 [-9223372036854775808],
 [4769247],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 1150],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [3617141],
 [-9223372036854775808, 367193039],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 272675775],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [47152719],
 [-9223372036854775808],
 [-9223372036854775808, 191143992],
 [-9223372036854775808],
 [-9223372036854775808, 6561349],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [78274706],
 [-9223372036854775808, 213399027],
 [-9223372036854775808],
 [-9223372036854775808],
 [213682673],
 [-9223372036854775808],
 [-9223372036854775808],
 [245234791],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [447991228],
 [-9223372036854775808],
 [-9223372036854775808],
 [398836513],
 [463762597],
 [-9223372036854775808],
 [-9223372036854775808, 297290152],
 [-9223372036854775808],
 [-9223372036854775808],
 [235249762],
 [-9223372036854775808],
 [-9223372036854775808],
 [59926106],
 [-9223372036854775808],
 [352219024],
 [-9223372036854775808],
 [-9223372036854775808],
 [209891379],
 [-9223372036854775808, 68743817],
 [-9223372036854775808],
 [-9223372036854775808],
 [120462019],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [172769030],
 [-9223372036854775808],
 [-9223372036854775808, 28568],
 [-9223372036854775808],
 [109337849],
 [-9223372036854775808, 68743821],
 [283343883],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [442823112],
 [179996894],
 [179973372],
 [233781288],
 [-9223372036854775808],
 [87336326],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [271472458],
 [-9223372036854775808, 108894],
 [298246367],
 [13391547],
 [15425739],
 [13773238],
 [13773226],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [295312062],
 [-9223372036854775808, 31881220],
 [-9223372036854775808],
 [152732983],
 [179899127],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [228807],
 [-9223372036854775808],
 [2273873],
 [1798804],
 [-9223372036854775808],
 [3373910],
 [364618895],
 [-9223372036854775808],
 [-9223372036854775808],
 [441687941],
 [-9223372036854775808],
 [-9223372036854775808],
 [9244815],
 [-9223372036854775808],
 [508257182],
 [76314484],
 [1711680],
 [-9223372036854775808],
 [-9223372036854775808],
 [4549698],
 [108826719],
 [-9223372036854775808],
 [2166160],
 [12902853],
 [-9223372036854775808],
 [1670113],
 [-9223372036854775808],
 [-9223372036854775808],
 [65672925],
 [-9223372036854775808, 1640256],
 [-9223372036854775808],
 [-9223372036854775808],
 [61240754],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [344900789],
 [-9223372036854775808],
 [-9223372036854775808, 336559588],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [228287081],
 [2473035],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 13213401],
 [-9223372036854775808],
 [480487288],
 [480487610],
 [7838421],
 [12637],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [22776],
 [9046195],
 [-9223372036854775808],
 [480937389],
 [480937448],
 [-9223372036854775808],
 [461709876],
 [-9223372036854775808, 1074],
 [11708295],
 [12620866],
 [51155584],
 [-9223372036854775808, 1732328],
 [3614355],
 [-9223372036854775808],
 [405339547],
 [127277],
 [-9223372036854775808],
 [-9223372036854775808, 461280813],
 [1540381],
 [-9223372036854775808],
 [-9223372036854775808, 6269836],
 [248886655],
 [-9223372036854775808],
 [-9223372036854775808],
 [425938649],
 [160067684],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [4498893],
 [-9223372036854775808],
 [3925541],
 [-9223372036854775808],
 [16519913],
 [77540598],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [459690817],
 [1620098],
 [-9223372036854775808],
 [-9223372036854775808],
 [188370822],
 [-9223372036854775808],
 [198849256],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [478311164],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [368093298],
 [2192185],
 [-9223372036854775808],
 [404725511],
 [246580785],
 [63929922],
 [432675646],
 [17187301],
 [-9223372036854775808, 12554],
 [1707546],
 [284857042],
 [33355479],
 [-9223372036854775808],
 [-9223372036854775808, 1268471],
 [390102977],
 [2123623],
 [26992],
 [-9223372036854775808],
 [1977],
 [-9223372036854775808],
 [2294657],
 [13543499],
 [-9223372036854775808],
 [-9223372036854775808],
 [4825824],
 [-9223372036854775808],
 [-9223372036854775808],
 [2628218],
 [-9223372036854775808],
 [6173930],
 [117161820],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [95269832],
 [6643641],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [33447746],
 [59976091],
 [350557686],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 453691312],
 [10595518],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [457228201],
 [-9223372036854775808],
 [-9223372036854775808],
 [22223540],
 [-9223372036854775808],
 [-9223372036854775808, 69502113],
 [-9223372036854775808],
 [9515295],
 [368875581],
 [-9223372036854775808, 1515899],
 [57779403],
 [-9223372036854775808, 24391],
 [-9223372036854775808],
 [-9223372036854775808, 1750998],
 [84863418],
 [411047313],
 [-9223372036854775808, 2097906],
 [35051010],
 [41519569],
 [64291166],
 [41519559],
 [25666372],
 [51155312],
 [41519570],
 [-9223372036854775808],
 [57533541],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 2606909],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [188994453],
 [-9223372036854775808],
 [-9223372036854775808],
 [258931615],
 [-9223372036854775808],
 [-9223372036854775808, 19460, 951255, 1619290],
 [5636074],
 [-9223372036854775808],
 [2389512],
 [-9223372036854775808],
 [-9223372036854775808, 62484525],
 [6896757],
 [-9223372036854775808, 1654825, 255153361],
 [-9223372036854775808],
 [-9223372036854775808],
 [16735201],
 [-9223372036854775808],
 [2910513],
 [-9223372036854775808],
 [-9223372036854775808],
 [6767, 8593],
 [-9223372036854775808, 3826],
 [178984899],
 [-9223372036854775808, 178984874],
 [60374608],
 [173029635],
 [-9223372036854775808, 371924497],
 [-9223372036854775808],
 [18714086],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [111088875],
 [-9223372036854775808],
 [178709351],
 [178984823],
 [178984851],
 [-9223372036854775808, 178715043],
 [178984802],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [340473011],
 [26469],
 [68718031],
 [77284844],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 246769614],
 [340329240],
 [340333009],
 [24747],
 [-9223372036854775808],
 [55993416],
 [55993414],
 [7848652],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [6427634],
 [9864512],
 [-9223372036854775808, 21215],
 [73208491],
 [-9223372036854775808],
 [12082074],
 [-9223372036854775808],
 [284236759],
 [367806826],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [408926921],
 [-9223372036854775808],
 [286297458],
 [-9223372036854775808, 131894152],
 [-9223372036854775808, 312103558],
 [253337165],
 [-9223372036854775808],
 [6896763],
 [267818006],
 [5809604],
 [84982697],
 [-9223372036854775808],
 [10347088],
 [-9223372036854775808],
 [-9223372036854775808],
 [138131894],
 [-9223372036854775808],
 [69377921],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [9389120, 186113439],
 [11650],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 345678530],
 [-9223372036854775808],
 [306359919],
 [429140522],
 [-9223372036854775808],
 [-9223372036854775808],
 [214530356],
 [-9223372036854775808],
 [-9223372036854775808],
 [236809122],
 [377873561],
 [73208566],
 [9506952],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808, 4230914],
 [-9223372036854775808, 1620179],
 [1997627],
 [41261585],
 [1813142],
 [-9223372036854775808],
 [367187846],
 [66346666],
 [66346648],
 [237629945],
 [-9223372036854775808],
 [-9223372036854775808],
 [-9223372036854775808],
 [84505369],
 [350847391],
 [-9223372036854775808],
 [-9223372036854775808],

In [90]:
## nested list loop------> SORT
lst22=[]
lst23=[]
index22=[]

for i in range(len(lst_id)):
    #for m in range(len(lst_id[i])):   
    lst22=sorted(lst_id[i])
    lst23.append(lst22)
        
print("DONE")

DONE

In [91]:
## convert back to string
for i in range(len(lst23)):
    for m in range(len(lst23[i])): 
        lst23[i][m]=str(lst23[i][m])
print("DONE")
#lst23

DONE

In [92]:
### nested list loop------> separate the KAP

lst25=[]
lst24=[]
index=[]
seperator='-'
for i in range(len(lst23)):
    for m in range(len(lst23[i])):   
        if (len(lst23[i])==1)&(lst23[i][m]=="-9223372036854775808"):
            ##KAP
            lst25.append("KAP")
            index.append(i)
        if (len(lst23[i])>=1)&('-9223372036854775808' in lst23[i]):
            lst25.append("BDRId:"+" "+seperator.join(lst23[i][1::])+" + KAP")
            #lst25.append(10)
            index.append(i)
        else:
            ##NUMS
            #lst25.append(2)
            lst25.append("BDRId:"+" "+seperator.join(lst23[i]))
            index.append(i)
            
list_of_tuples = list(zip(index, lst25))
sub= pd.DataFrame(list_of_tuples, columns = ['index', 'Profile Sub id']) 
sub=sub.drop_duplicates(subset=['index'], keep="first")
subresult = pd.merge(group_id, sub, left_index=True, right_on="index", how='inner')
subresult=subresult.reset_index()
print("DONE")

DONE

In [93]:
#subresult.to_excel("QA3334.xlsx")

In [122]:
subresult[0:10]

,level_0,Company Name *,old_id,index,Profile Sub id
0,0,(INTECH/5132)NOMURA ASSET MANAGEMENT CO LTD-TH...,[72553409],0,BDRId: 72553409
1,1,"(INTECH/5140)NIKKO ASSET MANAGEMENT CO, LTD-TH...",[72553413],1,BDRId: 72553413
2,2,"(INTECH/5142)SUMITOMO MITSUI TRUST BANK, LTD.-...",[72837076],2,BDRId: 72837076
3,3,"(INTECH/5154)NIKKO ASSET MANAGEMENT CO, LTD-TH...",[72553411],3,BDRId: 72553411
4,4,"(INTECH/I5157)SUMITOMO MITSUI TRUST BANK, LTD-...",[72553403],4,BDRId: 72553403
5,5,075A - PHS ITP DOMESTIC FI,[60030172],5,BDRId: 60030172
6,6,0890696 B.C. LTD,[363418982],6,BDRId: 363418982
7,7,1-3 YEAR CREDIT BOND INDEX NON-LENDABLE FUND,[267373735],7,BDRId: 267373735
8,8,100 WALNUT LLC,[507135948],8,BDRId: 507135948
9,9,10036803 CANADA INC,[-9223372036854775808],9,KAP

In [95]:
##len==1 and lst23[i][m]<0--> append KAP

# Look Back Date (Skip)

In [96]:
# ## the fake replace date need to be changed in the DEC 2020
# #data_new=pd.read_excel("country_cleaned_socgen_c1.xlsx")
# data=data_new.copy()
# data["Lookback Period Start date"]=data["Lookback Period Start date"].replace(np.nan,"12/12/2040")

# ## need to be completed the grouping
# look_back=data.groupby(['Company Name *']).agg({'Lookback Period Start date':'unique'})
# look_back.reset_index(inplace=True)

In [97]:
# ## convert list of array to nested list
# lst=look_back["Lookback Period Start date"].to_list()
# lst11=[]
# for i in range(len(lst)):
#     lst11.append(lst[i].tolist())
# lst11

In [98]:
# ## change str to datetime object
# for i in range(len(lst11)):
#     for m in range(len(lst11[i])):
#         if type(lst11[i][m])==str:
#             lst11[i][m]=datetime.strptime(lst11[i][m], "%m/%d/%Y").strftime('%Y-%m-%d')
#             lst11[i][m]=datetime.strptime(lst11[i][m], '%Y-%m-%d')
# print("Done")

In [99]:
# ## get the smallest in the sub list
# lst2=[]
# for i in range(len(lst11)):
#     t=min(lst11[i])
#     lst2.append(t)
# print("Done")

In [100]:
# ## change back to str for replace
# for i in range(len(lst2)):
#     lst2[i]=lst2[i].strftime('%Y-%m-%d')
# print("Done")

In [101]:
# look_back["Lookback Period Start date_final"]=lst2
# look_back["Lookback Period Start date_final"]=look_back["Lookback Period Start date_final"].replace("2040-12-12",np.nan)
# look_back

In [102]:
#look_back.to_excel("look_back_qa.xlsx")

# ONNS PROJECT (Skip)

In [103]:
# #data_new=pd.read_excel("country_cleaned_socgen_c1.xlsx")
# data=data_new.copy()

# ## grouping
# onns=data.groupby(['Company Name *']).agg({'Profile status':'unique'})
# onns.reset_index(inplace=True)

In [104]:
# ## convert to the nested list
# lst3=onns["Profile status"].to_list()
# lst4=[]
# for i in range(len(lst3)):
#     lst4.append(lst3[i].tolist())

In [105]:
# ## nested list loop
# lst5=[]
# index5=[]

# for i in range(len(lst4)):
#     for m in range(len(lst4[i])):
#         if lst4[i][m]=="ONNS-Project":
#             lst5.append("ONNS-Project")
#             index5.append(i)

# list_of_tuples = list(zip(index5, lst5))
# onns1 = pd.DataFrame(list_of_tuples, columns = ['index', 'Profile status_final']) 
# onnsresult = pd.merge(onns, onns1, left_index=True, right_on="index", how='outer')
# onnsresult=onnsresult.reset_index()

In [106]:
# data_frames1 = [df_merged4, look_back, onnsresult]
# df_merged2 = reduce(lambda  left,right: pd.merge(left,right,on=['Company Name *'],
#                                             how='inner'), data_frames1)
# df_merged2.columns

In [107]:
#df_merged2.to_excel("QA6.xlsx")

# Submission Type (Done)

In [108]:
# data_new=pd.read_excel("country_cleaned_socgen_c1.xlsx")
# data_new["Country"]
data_new["Country"]=data_new["Country"].astype(str)

In [109]:
#concate the data and deduplicate
data_new["concat"] = data_new['Address'].map(str) +' ' + data_new['City'].map(str) +' ' + data_new['StateProv'].map(str)+' ' + data_new['ZipPostal'].map(str)+' '+data_new['Country'].map(str)
data_dedupli=data_new.drop_duplicates(subset=['Company Name *','concat'], keep="first")
data_dedupli

g=data_dedupli.groupby(['Company Name *']).agg({'Address':lambda x: list(x),
                                              'City':lambda x: list(x),
                                             'StateProv':lambda x: list(x),
                                             'ZipPostal':lambda x: list(x),
                                             "Country":lambda x: list(x)})



## change into workbench format: need to include city, state, country name change
g.reset_index(inplace=True)

In [110]:
## get the concated country column
c_code=g[["Company Name *","Country"]]
c_code

## convert to thre nested list
lst7=c_code["Country"].to_list()
lst8=[]
for i in range(len(lst7)):
    lst8.append(lst7[i])
#lst8

In [111]:
## apply multinational rule
lst9=[]
index9=[]

for i in range(len(lst8)):
    for m in range(len(lst8[i])):
        if (lst8[i][m]=="") or (lst8[i][m]==" ") or (lst8[i][m]=="nan") or(lst8[i][m]==np.nan) or (lst8[i][m]=="NAN"):
            lst9.append("MULTINATIONAL")
            index9.append(i)

list_of_tuples = list(zip(index9, lst9))
subtype = pd.DataFrame(list_of_tuples, columns = ['index', 'Submission Type_final']).drop_duplicates(subset=['index',"Submission Type_final"], keep="first")
submissonResult = pd.merge(c_code, subtype, left_index=True, right_on="index", how='outer')
submissonResult=submissonResult.reset_index()

In [112]:
#submissonResult.to_excel("sub_qa.xlsx")

In [121]:
submissonResult[0:10]

,level_0,Company Name *,Country,index,Submission Type_final
0,2627,(INTECH/5132)NOMURA ASSET MANAGEMENT CO LTD-TH...,[JAPAN],0,NaN
1,2627,"(INTECH/5140)NIKKO ASSET MANAGEMENT CO, LTD-TH...",[JAPAN],1,NaN
2,2627,"(INTECH/5142)SUMITOMO MITSUI TRUST BANK, LTD.-...",[JAPAN],2,NaN
3,2627,"(INTECH/5154)NIKKO ASSET MANAGEMENT CO, LTD-TH...",[JAPAN],3,NaN
4,2627,"(INTECH/I5157)SUMITOMO MITSUI TRUST BANK, LTD-...",[JAPAN],4,NaN
5,2627,075A - PHS ITP DOMESTIC FI,[UNITED STATES],5,NaN
6,2627,0890696 B.C. LTD,[CANADA],6,NaN
7,2627,1-3 YEAR CREDIT BOND INDEX NON-LENDABLE FUND,[UNITED STATES],7,NaN
8,2627,100 WALNUT LLC,[UNITED STATES],8,NaN
9,2627,10036803 CANADA INC,[CANADA],9,NaN

# merge all

In [114]:
data_frames5 = [df_merged4, subresult, submissonResult,h]
df_merged5 = reduce(lambda  left,right: pd.merge(left,right,on=['Company Name *'],
                                            how='outer'), data_frames5)

In [115]:
df_merged5.columns
len(df_merged5)

22028

In [120]:
df_merged5[0:100]

,Company Name *,Address,Location 1 Address,Location 2 Address,Location 3 Address,Location 4 Address,Location 5 Address,Location 6 Address,Location 7 Address,Location 8 Address,...,index_x,Submission ID,level_0_y,Country,index_y,Submission Type,Additional Data Value 2,Additional Data Label 1,Additional Data Value 1,Additional Data Label 2
0,(INTECH/5132)NOMURA ASSET MANAGEMENT CO LTD-TH...,250 S. AUSTRALIAN AVENUE,2-2-2 OTEMACHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,BDRId: 72553409,2627,[JAPAN],0,NaN,[A-5389],Lookback Date,01/01/2020,Source Rows
1,"(INTECH/5140)NIKKO ASSET MANAGEMENT CO, LTD-TH...",250 S. AUSTRALIAN AVENUE,"2-11-3, HAMAMATSUCHO",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,BDRId: 72553413,2627,[JAPAN],1,NaN,[A-5391],Lookback Date,01/01/2020,Source Rows
2,"(INTECH/5142)SUMITOMO MITSUI TRUST BANK, LTD.-...",250 S. AUSTRALIAN AVENUE,1-8-11 HARUMI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,BDRId: 72837076,2627,[JAPAN],2,NaN,[A-5402],Lookback Date,01/01/2020,Source Rows
3,"(INTECH/5154)NIKKO ASSET MANAGEMENT CO, LTD-TH...",250 S. AUSTRALIAN AVENUE,"2-11-3, HAMAMATSUCHO",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,BDRId: 72553411,2627,[JAPAN],3,NaN,[A-5390],Lookback Date,01/01/2020,Source Rows
4,"(INTECH/I5157)SUMITOMO MITSUI TRUST BANK, LTD-...",250 S. AUSTRALIAN AVENUE,"2-11-3, HAMAMATSUCHO",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,BDRId: 72553403,2627,[JAPAN],4,NaN,[A-5388],Lookback Date,01/01/2020,Source Rows
5,075A - PHS ITP DOMESTIC FI,1209 ORANGE ST,2 SEAPORT LANE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,BDRId: 60030172,2627,[UNITED STATES],5,NaN,[A-4802],Lookback Date,01/01/2020,Source Rows
6,0890696 B.C. LTD,2300 - 1055 DUNSMUIR STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,BDRId: 363418982,2627,[CANADA],6,NaN,[A-10131],Lookback Date,01/01/2020,Source Rows
7,1-3 YEAR CREDIT BOND INDEX NON-LENDABLE FUND,400 HOWARD STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7,BDRId: 267373735,2627,[UNITED STATES],7,NaN,[A-8788],Lookback Date,01/01/2020,Source Rows
8,100 WALNUT LLC,122 QUENTIN AVE,20 COMMERCE DR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8,BDRId: 507135948,2627,[UNITED STATES],8,NaN,[A-11672],Lookback Date,01/01/2020,Source Rows
9,10036803 CANADA INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9,KAP,2627,[CANADA],9,NaN,[B-1],Lookback Date,01/01/2020,Source Rows
10,"101 MERRIMAC HOLDINGS, LLC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,KAP,2627,[UNITED STATES],10,NaN,[B-2],Lookback Date,01/01/2020,Source Rows
11,"101 MERRIMAC OWNER, LLC",1209 ORANGE ST,"234 CLARENDON STREET,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,BDRId: 479233120,2627,[UNITED STATES],11,NaN,[A-11448],Lookback Date,01/01/2020,Source Rows
12,"101 MERRIMAC, INC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12,KAP,2627,[UNITED STATES],12,NaN,[B-3],Lookback Date,01/01/2020,Source Rows
13,"101 MERRIMAC, LLC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13,KAP,2627,[UNITED STATES],13,NaN,[B-4],Lookback Date,01/01/2020,Source Rows
14,1029 GEARY JV LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14,KAP,2627,[UNITED STATES],14,NaN,[B-5],Lookback Date,01/01/2020,Source Rows
15,1029 GEARY STREET PROPERTY LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,KAP,2627,[UNITED STATES],15,NaN,[B-6],Lookback Date,01/01/2020,Source Rows
16,10614408 CANADA LIMITED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16,KAP,2627,[CANADA],16,NaN,[B-7],Lookback Date,01/01/2020,Source Rows
17,10618667 CANADA INC,1000 DE LA GAUCHETIERE WEST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17,BDRId: 323561654,2627,[CANADA],17,NaN,[A-9590],Lookback Date,01/01/2020,Source Rows
18,1069024 ONTARIO LIMITED,2 QUEEN STREET EAST,595 BURRARD STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18,BDRId: 180437030,2627,[CANADA],18,NaN,[A-7269],Lookback Date,01/01/2020,Source Rows
19,10814253 CANADA INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19,KAP,2627,[UNITED STATES],19,NaN,[B-8],Lookback Date,01/01/2020,Source Rows
20,1102952 B.C. UNLIMITED LIABILITY COMPANY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20,KAP,2627,[CANADA],20,NaN,[B-9],Lookback Date,01/01/2020,Source Rows
21,1185-9576 QUEBEC INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21,KAP,2627,[CANADA],21,NaN,[B-10],Lookback Date,01/01/2020,Source Rows
22,1199SEIU HEALTH CARE EMPLOYEES PENSION FUND,251 LITTLE FALLS DRIVE,251 LITTLE FALLS DRIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22,BDRId: 74152393,2627,[UNITED STATES],22,NaN,[A-5431],Lookback Date,01/01/2020,Source Rows
23,1212770 BC LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,KAP,2627,[CANADA],23,NaN,[B-11],Lookback Date,01/01/2020,Source Rows
24,1397225 ONTARIO LIMITED,5650 YONGE STREET,5650 YONGE STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24,BDRId: 226011210,2627,[CANADA],24,NaN,[A-8080],Lookback Date,01/01/2020,Source Rows
25,145 SPRING STREET PARTNERS LLC,160 GREENTREE DR,28 LIBERTY STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25,BDRId: 456378776,2627,[UNITED STATES],25,NaN,[A-11278],Lookback Date,01/01/2020,Source Rows
26,16 TECH COMMUNITY CORPORATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26,KAP,2627,[UNITED STATES],26,NaN,[B-16],Lookback Date,01/01/2020,Source Rows
27,"161 N CLARK OWNER, LLC",1209 ORANGE ST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27,BDRId: 365521004,2627,[UNITED STATES],27,NaN,[A-10166],Lookback Date,01/01/2020,Source Rows
28,1625 EYE STREET GP LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28,KAP,2627,[UNITED STATES],28,NaN,[B-12],Lookback Date,01/01/2020,Source Rows
29,1625 EYE STREET HOLDINGS LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29,KAP,2627,[UNITED STATES],29,NaN,[B-13],Lookback Date,01/01/2020,Source Rows
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,26 BROADWAY TRUST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70,KAP,2627,[AUSTRALIA],70,NaN,[B-51],Lookback Date,01/01/2020,Source Rows
71,2694519 ONTARIO INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71,KAP,6,[ ],71,MULTINATIONAL,"[B-49, B-50]",Lookback Date,01/01/2020,Source Rows
72,280 CAPMARKETS LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72,KAP,2627,[UNITED STATES],72,NaN,[B-52],Lookback Date,01/01/2020,Source Rows
73,280 SECURITIES LLC,251 LITTLE FALLS DRIVE,251 LITTLE FALLS DRIVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73,BDRId: 338615996,2627,[UNITED STATES],73,NaN,[A-9800],Lookback Date,01/01/2020,Source Rows
74,"3 MAST HOLDINGS, LLC",1900 GALLOWS ROAD SUITE 700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74,BDRId: 284236603 + KAP,2627,[UNITED STATES],74,NaN,"[A-8976, B-78]",Lookback Date,01/01/2020,Source Rows
75,3 MR INC,USA,USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75,BDRId: 355730209,2627,[UNITED STATES],75,NaN,[A-10073],Lookback Date,01/01/2020,Source Rows
76,3041 PECK ROAD SOLAR LLC,1209 ORANGE ST,6200 N. WASHINGTON STREET UNIT 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76,BDRId: 273502858,2627,[UNITED STATES],76,NaN,[A-8876],Lookback Date,01/01/2020,Source Rows
77,"305 HYDE JV, LLC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,77,KAP,2627,[UNITED STATES],77,NaN,[B-53],Lookback Date,01/01/2020,Source Rows
78,305 HYDE STREET PROPERTY LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78,KAP,2627,[UNITED STATES],78,NaN,[B-54],Lookback Date,01/01/2020,Source Rows
79,3233 ALAMO LLC,USA,1431 GREENWAY DRIVE STE 155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,79,BDRId: 449640165,2627,[UNITED STATES],79,NaN,[A-11227],Lookback Date,01/01/2020,Source Rows
80,3233 MANAGER INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80,KAP,2627,[UNITED STATES],80,NaN,[B-55],Lookback Date,01/01/2020,Source Rows
81,325 FILLMORE LLC,1209 ORANGE STREET,100 FILLMORE STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81,BDRId: 306794122 + KAP,2627,[UNITED STATES],81,NaN,"[A-9283, B-56]",Lookback Date,01/01/2020,Source Rows
82,"3301 WINDY RIDGE PARKWAY, LLC",1209 ORANGE ST,706 23RD STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,82,BDRId: 448834705,2627,[UNITED STATES],82,NaN,[A-11219],Lookback Date,01/01/2020,Source Rows
83,333753774-PORTS AMERICA GROUP INC,1209 ORANGE STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83,KAP,2627,[UNITED STATES],83,NaN,[B-57],Lookback Date,01/01/2020,Source Rows
84,33RD STREET PARTNERS JV LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,84,KAP,2627,[UNITED STATES],84,NaN,[B-58],Lookback Date,01/01/2020,Source Rows
85,345 NOMINEES LTD,20 GENESIS CLOSE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85,BDRId: 218558725,2627,[CAYMAN ISLANDS],85,NaN,[A-7979],Lookback Date,01/01/2020,Source Rows
86,"345679952-WATERMARK TERMINAL SOLUTIONS, LLC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86,KAP,2627,[UNITED STATES],86,NaN,[B-59],Lookback Date,01/01/2020,Source Rows
87,"346142044-PORTS AMERICA TERMINAL HOLDINGS II, INC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87,KAP,2627,[UNITED STATES],87,NaN,[B-60],Lookback Date,01/01/2020,Source Rows
88,347 EDDY JV LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88,KAP,2627,[UNITED STATES],88,NaN,[B-61],Lookback Date,01/01/2020,Source Rows
89,347 EDDY STREET PROPERTY LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89,KAP,2627,[UNITED STATES],89,NaN,[B-62],Lookback Date,01/01/2020,Source Rows
90,36 SOUTH CAPITAL ADVISORS LLP,BERKELEY SQUARE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90,BDRId: 13140944,2627,[UNITED KINGDOM],90,NaN,[A-3613],Lookback Date,01/01/2020,Source Rows
91,360 TRADING NETWORKS INC,874 WALKER RD,521 FIFTH AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91,BDRId: 64185362,2627,[UNITED STATES],91,NaN,[A-5041],Lookback Date,01/01/2020,Source Rows
92,360 TREASURY SYSTEMS AG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92,KAP,2627,[GERMANY],92,NaN,[B-63],Lookback Date,01/01/2020,Source Rows
93,361 CAPITAL LLC,1209 ORANGE STREET,4600 SOUTH SYRACUSE STREET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93,BDRId: 4719724,2627,[UNITED STATES],93,NaN,[A-2642],Lookback Date,01/01/2020,Source Rows
94,371 TURK JV LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94,KAP,2627,[UNITED STATES],94,NaN,[B-64],Lookback Date,01/01/2020,Source Rows
95,371 TURK STREET PROPERTY LLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95,KAP,2627,[UNITED STATES],95,NaN,[B-65],Lookback Date,01/01/2020,Source Rows
96,"39001 MONTEREY AVE SOLAR, LLC",1209 ORANGE STREET,6200 N. WASHINGTON STREET UNIT 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,96,BDRId: 273502646,2627,[UNITED STATES],96,NaN,[A-8873],Lookback Date,01/01/2020,Source Rows
97,3955338 CANADA INC,"1350 RENE-LEVESQUE BLVD, 25 FLOOR",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97,BDRId: 238210762,2627,[CANADA],97,NaN,[A-8267],Lookback Date,01/01/2020,Source Rows
98,3G CAPITAL PARTNERS II LP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,98,KAP,2627,[UNITED STATES],98,NaN,[B-66],Lookback Date,01/01/2020,Source Rows
99,3G CAPITAL PARTNERS LP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99,KAP,2627,[UNITED STATES],99,NaN,[B-67],Lookback Date,01/01/2020,Source Rows

In [117]:
# re-format
df_merged5["Additional Data Label 1"]="Lookback Date"
df_merged5["Additional Data Value 1"]="01/01/2020"
df_merged5["Additional Data Label 2"]="Source Rows"

df_merged5=df_merged5.rename(columns={"Submission Type_final":"Submission Type",
                     "Profile Sub id":"Submission ID",
                     "identifier":"Additional Data Value 2",
                     "City_x":"City",
                     "StateProv_x_y":"StateProv",
                     "ZipPostal_x_y":"ZipPostal",
                     "Country_x_y":"Country"})

In [119]:
#df_merged5.to_excel("final_qa_last10.xlsx")